### PR TITLE
Add performance test

### PR DESCRIPTION
**Pull request by pmconrad**
This is a test case for the famous "100,000 transactions per second", referred to in my presentation at BitFest.

### CODE REVIEW

**Comment by abitmore** [comment]
Good job. We'd better update Wiki after merged this.

**Comment by abitmore** [comment]
Better wrap long lines.

**Comment by pmconrad** [comment]
@cedar-book can you please add a link to https://github.com/bitshares/bitshares-core/tree/develop/tests/performance in the documentation? Perhaps next to my bitfest presentation download. Not sure if there's another page dealing with performance.
Thanks!

**Comment by cedar-book** [comment]
@pmconrad , I added the link to two locations.

(1) BitShares Community Events
http://dev.bitshares.works/en/master/references/info_bts_events.html

(2) Developer Guide (Tutorials) - Performance section
http://dev.bitshares.works/en/master/bts_guide/tutorials/index.html#performance

**Comment by pmconrad** [comment]
Excellent, thanks!

**Pull request merged**
