### PR TITLE
extend static_variant with is_type() method

### PR DESCRIPTION
**Pull request by crypto-ape**
Hey Monkeys!

This PR implements the proposal from the issue #1769 .

Ape out!

### CODE REVIEW

**Comment by oxarbitrage** [comment]
This pull is not building, please check travis output: https://travis-ci.org/bitshares/bitshares-core/builds/544288497?utm_source=github_status&utm_medium=notification

**Comment by crypto-ape** [comment]
The actual feature is implemented within the fc library, I was just about tu make a PR there.
Please, how do you await such a necessary change from a submodule to be provided other than in custom PR within that submodule?

**Comment by oxarbitrage** [comment]
Need to send pull request to FC, after approved and merged a bump FC commit should be included in this one.

**Comment by crypto-ape** [comment]
Okay. Here it goes.
https://github.com/bitshares/bitshares-fc/pull/138

**Comment by oxarbitrage** [comment]
merged https://github.com/bitshares/bitshares-fc/pull/138 , please bump FC here. 

for example, last merged bump is included in https://github.com/bitshares/bitshares-core/pull/1768 at commit: https://github.com/bitshares/bitshares-core/pull/1768/commits/90efe68bebc8ed03e4ff6820c45df6a4aa0ad577

**Comment by abitmore** [comment]
@crypto-ape commands:
```
cd libraries/fc
git checkout master
git pull
cd ..
git add fc
git commit
```

**Comment by crypto-ape** [comment]
Done.

**Pull request merged**
