### PR TITLE
remove the not required logging

### PR DESCRIPTION
**Pull request by crazybits**
there is redundant log printed in the cli wallet console while publishing the price feed thru witness node, this PR is to remove the not required logging.

### CODE REVIEW

**Comment by oxarbitrage** [comment]
- please send pull request to `develop` branch. 
- instead of comment please just remove the log lines.
- besides that 2 things looks good.

**Comment by abitmore** [comment]
I changed the base branch to `develop` (by editing the subject), but seems it need a rebase.

**Comment by oxarbitrage** [comment]
maybe we just create another one: https://github.com/bitshares/bitshares-core/pull/519 and merge this new one in case we suffer some conflict when we merge the develop into master on next release. let me know what do you think.

**Comment by abitmore** [comment]
I'd recommend keep the original contributor info. Will merge https://github.com/bitshares/bitshares-core/pull/522. Closing this one.

**Pull request closed without merging**
