### PR TITLE
Merge develop to hardfork for Rel 4.0

### PR DESCRIPTION
**Pull request by jmjatlanta**
This will merge the latest updates to the development branch into the hardfork branch in preparation for the Protocol Upgrade release 4.0

### CODE REVIEW

**Comment by jmjatlanta** [comment]
> It looks like the compiler uses too much RAM for docker:

Here is a bit more of the log:
```
Scanning dependencies of target graphene_protocol_custom_auths
[ 40%] Building CXX object libraries/protocol/CMakeFiles/graphene_protocol_custom_auths.dir/custom_authorities/restriction_predicate.cpp.o
[ 40%] Building CXX object libraries/protocol/CMakeFiles/graphene_protocol_custom_auths.dir/custom_authorities/list_1.cpp.o
[ 40%] Building CXX object libraries/protocol/CMakeFiles/graphene_protocol_custom_auths.dir/custom_authorities/list_2.cpp.o
[ 40%] Building CXX object libraries/protocol/CMakeFiles/graphene_protocol_custom_auths.dir/custom_authorities/list_3.cpp.o
[ 42%] Building CXX object libraries/protocol/CMakeFiles/graphene_protocol_custom_auths.dir/custom_authorities/list_4.cpp.o
[ 42%] Building CXX object libraries/protocol/CMakeFiles/graphene_protocol_custom_auths.dir/custom_authorities/list_5.cpp.o
c++: internal compiler error: Killed (program cc1plus)
```
@nathanhourt any ideas?

**Comment by nathanhourt** [comment]
I think docker's limit is [2GB of RAM](https://forums.docker.com/t/automated-build-resource-restrictions/1413)... I don't think that's feasible.

**Comment by pmconrad** [comment]
I think the limit is more like 5G, at least on my machine list_4.cpp (actually all except list_5) stays below 5G while list_5 is above.
Attempting a simple fix in #2028.

A better fix might be to externalize `make_predicate` specializations, which would also bring down compile time for all those list_*x*.cpp files. I can't see how to externalize them all using template metaprogramming, and I'm too lazy to type them all out. Any idea, @nathanhourt ? :-)

**Comment by nathanhourt** [comment]
> I think the limit is more like 5G, at least on my machine list_4.cpp (actually all except list_5) stays below 5G while list_5 is above.
> Attempting a simple fix in #2028.
> 
> A better fix might be to externalize `make_predicate` specializations, which would also bring down compile time for all those list__x_.cpp files. I can't see how to externalize them all using template metaprogramming, and I'm too lazy to type them all out. Any idea, @nathanhourt ? :-)

I spent some time trying to `extern` things and bring the build complexity down, but I didn't get anywhere fast, and came to the same conclusion: I can do better later.

Eventually, I'd like to make an `object_explorer` template that takes a reflected object and generates runtime accessible information about its structure, then allows the construction at runtime of functors that inspect through the object. It is my expectation that this type would dramatically cut down the complexity of the build without being a significant increase of runtime complexity. But that template alone will be massively complex, and I didn't get very far with it before realizing it's going to take a lot of time to create.

**Pull request merged**
