### PR TITLE
Update docker configuration

### PR DESCRIPTION
**Pull request by beokuu**
##  What changed
+ rebased the image on ubuntu 16.04 and rewrote the Dockerfile following the instructions in README.md
+ running and customizing the image is now done with docker-compose if it is supported
+ removed the `docker/` directory
+ added a .dockerignore to prevent some useless compilation
#  Usage with docker-compose
+ Install [docker](https://docs.docker.com/engine/installation/) and [docker-compose](https://docs.docker.com/compose/install/)
+ Clone the repository, get on the revision you want and update the submodules:
```
git clone https://github.com/beokuu/bitshares-core.git
cd bitshares-core
git checkout update-docker-configuration
git submodule update --init --recursive
```
+ Do `docker-compose up -d` to build bitshare and start the node in the background
+ Grab a tea while bitshares compiles
+ When the compilation is done, do `docker-compose down` to stop the node
+ Customize `witness_node_data_dir/config.ini`, for example set
```
rpc-endpoint = 127.0.0.1:8090
```
(You might need to bind to 0.0.0.0 if you want to expose your node since knowing the container ip there is not trivial)
+ Add the port(s) needed in `docker-compose.yml`, for example:
```
    volumes:
      - ...
    ports:
      - 8090:8090
      - 9090:9090
```
+ Start the node again with `docker-compose up -d` (see [compose documentation](https://docs.docker.com/compose/overview/), you can do a lot of stuff with it)
## Access the cli wallet
+ Do `docker-compose exec witness bash` to enter the container
+ In the container, do `./programs/cli_wallet/cli_wallet`
## Change the data directory location
To change the data directory location on the host you need to modify the `docker-compose.yml` file like so
```
    volumes:
      - /PATH/TO/DATA/DIR:/bitshares/witness_node_data_dir
```
## Logs
To see the logs either do
+ `docker-compose logs` while the node is running

or

+ `docker-compose up` without the `-d` option to run the node 
## Update the image
+ `docker-compose build` will recompile bitshares if you updated your repository
#  Other
+ If the PR gets merged we should put the Usage part of this comment in some kind of doc 
+ I'll try to maintain the docker stuff if this gets merged
+ I know this is not easily customizable for now but it should build and run on everything that supports docker (even with just `docker build` `docker run`)

### CODE REVIEW

**Comment by beokuu** [comment]
I'm confused about what base i should be using..

**Comment by pmconrad** [comment]
Please base on develop.

**Comment by oxarbitrage** [comment]
this is great, thank you very much for makin iot. i am going to test it as well. as @pmconrad mentions you need to push to the `develop` branch.

**Comment by beokuu** [comment]
Thanks for the review, sorry for the mistakes :P

----

 > should specify the minimum version required to get a working result

I chose version 3 because there is features in version 2 that are not supported in version 3 and I wanted to prevent locking an old version of docker but you're probably right.

----

> removed ".git" (...) Did you really test that?

Nope :/
I added that because the `COPY . /bitshares` would have caused the image to rebuild every-time a file that is not in the .dockerignore would change and if I was committing a change to dockerfile it would recompile everything from scratch even if the change was after the compilation step.
But that is clearly not a good solution.
I should probably make another Dockerfile for dev with the repo as a volume.

----

> My build ran out of diskspace

I wanted to do a size reduction pass but forgot.

----

> I'd expected that the resulting image is optimized for production use

I was making the image so I could develop for bitshares but a production image makes a lot more sense for docker. I'll try to make an env file for docker that allow for a dev./prod. toggle with prod. by default.

+ Are you sure I can drop everything that is not a binary in `programs/`?
+ Is `CMAKE_BUILD_TYPE` the only flag I need to care about?

----

>CMake complains that it can't find readline, curses and bzip2 headers. Since cli_wallet is being built you should add at least the readline development files.

Will do.

**Comment by beokuu** [comment]
The image is now 1.12GB instead of the previous 7+GB.
Still not enough I guess.
If the executables are self contained (only depend on linux kernel/all libs statically linked (not 100% about this part)) we could base the container from a scratch image, copy the binaries and be done while having an extremely small image. I never done microcontainers, could be interesting.

**Comment by Zapata** [comment]
Did you look at [crazybits images](https://github.com/crazybits/docker-compose-files/tree/master/bitshares)?
They are already "production" ready, modular and smaller. (@beokuu I think the compîled code it what makes your container bigger).

May be production images could be put in a dedicated official repo (forked from the one of beokuu), and just keep a dev image in this repo.

Also it might be interesting to upgrade the Vagrant file to use the same docker "dev" container.

**Comment by n0izn0iz** [comment]
Definitely put this in an official repo and remove the Dockerfile here, this would prevent useless work. The crazybits image depend on the docker folder so this would have broke them..

**Comment by beokuu** [comment]
Thanks @Zapata !
If you don't fork the repos at least put a link in the README and remove the Dockerfile in this repo, this would prevent useless work.

**Comment by xeroc** [comment]
Clean an simple solution. Nice!

**Comment by beokuu** [comment]
I've replaced the code with a development oriented image, that's what I'm using to dev on arch linux.
With:
```
./docker/builder/run.sh
```
You access a dev container with an unprivileged user which home is a volume of the repository. The default shell is fish, you can use git, cmake, make and other tools in the image.

**Comment by xeroc** [comment]
Just to be clear on this .. the purpose of this Dockerfile is to offer a console that has the sources of bitshares and all the required dependencies installed in it? I am asking because I don't even see code that compiles bitshares in this PR.

**Comment by oxarbitrage** [comment]
closing as @xeroc new docker configurations replace this and no further comment was made by author.

**Pull request closed without merging**
