### PR TITLE
add link to memory reduction wiki

### PR DESCRIPTION
**Pull request by oxarbitrage**
https://github.com/bitshares/bitshares-core/issues/378

### CODE REVIEW

**Comment by abitmore** [comment]
I think it's good if we add "Currently a full node requires 40GB of RAM" to the description.

**Comment by oxarbitrage** [comment]
definitely. was going to ask that info in the dev channel today as i don't have even close to the required RAM needed to run a full node but i forgot. added this info to the second sentence of the wiki and into README.

**Comment by pmconrad** [comment]
I disagree - don't put values in there that need constant updating.

**Comment by oxarbitrage** [comment]
what do you think on removing from README and leave it in the wiki page with the date ? i think the number should be somewhere to people really know how much RAM you need to run a full node before they even try it and gets frustrated with errors.

**Comment by pmconrad** [comment]
Well, perhaps leave it there but add a timestamp and a warning that it's growing quickly.

**Comment by pmconrad** [comment]
+1

**Pull request merged**
