### PR TITLE
Implement grouped orders plugin

### PR DESCRIPTION
**Pull request by abitmore**
PR for #639.

Configuration changes (need a restart but no need to replay after changed):
```
# api-access:
# new "orders" api enabled by default and everyone have access to it,
# if you use an api-access file, need to add it to your file

# plugins:
# new "grouped_orders" plugin enabled by default if `plugins` option is not configured,
# if you use `plugins` option, add it
plugins = [your_plugin_list] grouped_orders

# tracked-groups:
# new option, default value is [10,100], means group orders by 0.1% and 1% price diff
# tracked-groups = [10,100]
```

New API's and related data structure:
```
         /**
          * @breif Get tracked groups configured by the server.
          * @return A list of numbers which indicate configured groups, of those, 1 means 0.01% diff on price.
          */
         flat_set<uint16_t> get_tracked_groups()const;

         /**
          * @breif Get grouped limit orders in given market.
          *
          * @param base_asset_id ID of asset being sold
          * @param quote_asset_id ID of asset being purchased
          * @param group Maximum price diff within each order group, have to be one of configured values
          * @param start Optional price to indicate the first order group to retrieve
          * @param limit Maximum number of order groups to retrieve (must not exceed 101)
          * @return The grouped limit orders, ordered from best offered price to worst
          */
         vector< limit_order_group > get_grouped_limit_orders( asset_id_type base_asset_id,
                                                               asset_id_type quote_asset_id,
                                                               uint16_t group,
                                                               optional<price> start,
                                                               uint32_t limit )const;

   struct limit_order_group
   {
      price         min_price; ///< possible lowest price in the group
      price         max_price; ///< possible highest price in the group
      share_type    total_for_sale; ///< total amount of asset for sale, asset id is min_price.base.asset_id
   };
```

Example of querying for best offers grouped by 0.1% price diff in CNY:BTS market (one side):

>$ curl -d '{"id":15,"method":"call","params":["orders","get_grouped_limit_orders",["1.3.113","1.3.0",10,null,2]]}' http://127.0.0.1:38690/rpc 2>/dev/null ;echo
>
>{"id":15,"jsonrpc":"2.0","result":[{"min_price":{"base":{"amount":44911,"asset_id":"1.3.113"},"quote":{"amount":300000,"asset_id":"1.3.0"}},"max_price":{"base":{"amount":755251,"asset_id":"1.3.113"},"quote":{"amount":5040051,"asset_id":"1.3.0"}},"total_for_sale":2965272},{"min_price":{"base":{"amount":753991,"asset_id":"1.3.113"},"quote":{"amount":5040051,"asset_id":"1.3.0"}},"max_price":{"base":{"amount":59880000,"asset_id":"1.3.113"},"quote":{"amount":400000000,"asset_id":"1.3.0"}},"total_for_sale":68176675}]}

### CODE REVIEW

**Comment by abitmore** [comment]
The plugin is implemented with `secondary_index`. As a result, no need to replay after applied the patch or changed configured `tracked-groups` parameter, but do need to restart, data will be reloaded at every restart. A side effect is need longer at startup. With default config (0.1% and 1% groups), it does need more RAM, but not much (I think it's around 1G).

**Comment by abitmore** [comment]
@oxarbitrage thanks. Fixed.

**Comment by abitmore** [comment]
Hmm, hold on, chain_test is still broken.

**Comment by abitmore** [comment]
Fixed.

**Comment by abitmore** [comment]
There might be something wrong in the code, since I've got many warning messages like this:
>2797842ms th_a       grouped_orders_plugin.cpp:191 remove_order         ] can not find the order group containing order for removing: {"id":"1.7.54434599","expiration":"2023-02-13T01:45:46","seller":"1.2.126083","for_sale":9954030,"sell_price":{"base":{"amount":9954030,"asset_id":"1.3.861"},"quote":{"amount":53749529,"asset_id":"1.3.113"}},"deferred_fee":92}

**Comment by abitmore** [comment]
The issue mentioned above is due to the lack of an override `insert()` function in `primary_index` class. Fixed.

**Comment by oxarbitrage** [comment]
got the same warns, trying the new version.

**Pull request merged**
