### PR TITLE
Rename option of debug witness plugin, fix #399

### LINKED ISSUE #399: Testnet "--private-key" command-line options is duplicated
and hence cannot be specified on the command-line, as it fails with the following error:

```Error parsing command line: option '--private-key' is ambiguous and matches different versions of '--private-key'```

this comes from the fact the both the `witness` plugin and the `debug-witness` define the `--private-key` option. A simple fix would be to rename the option for the debug-witness plugin to something like `--private-key-testnet` or something to that effect.

I'll submit a pull request if I can get confirmation that `--private-key-testnet` is a good naming, otherwise please suggest an alternative and I'll implement that. Thanks!

### PR DESCRIPTION
**Pull request by abitmore**
This will get around #399.

### CODE REVIEW

**Comment by pmconrad** [comment]
Thinking about it - the --private-key option is a security risk. CLI options of running programs are visible to all users on the machine.
Perhaps with should remove to CLI option from both plugins and leave only the config file option?

**Comment by abitmore** [comment]
@pmconrad your suggestion makes sense, but perhaps better discuss it in a new ticket. At this moment we need the CLI parameter due to #149, and we need a usable release. This PR doesn't introduce additional risk.

**Comment by pmconrad** [comment]
Good. Thanks @abitmore !

**Comment by wackou** [comment]
> Thinking about it - the --private-key option is a security risk. CLI options of running programs are visible to all users on the machine.
Perhaps with should remove to CLI option from both plugins and leave only the config file option?

Please don't, I agree with the assessment that it's a security risk, but it'd be better to document it this way (if not obvious already that, being a private key, you should be extra-careful where you use it), or even print a warning when used. I am using constantly (for automated deploys, etc. and pass all the options via the commandline) and it would be a pain for me to deal without it. Some other reasons that I think do not warrant removing it:
- having it in the config.ini doesn't really make it that more secure, you could argue that there's some unix user protection, but I'd counter argue that anyone having access to your machine, where gcc is most likely installed, can easily find a local privilege escalation, get root, and get to your file.
- it being a signing key, it is less critical to lose access to it than, say, your owner or active key

Thanks for reconsidering.

**Pull request merged**
