### PR TITLE
Minor stuff fixed during testnet release

### PR DESCRIPTION
**Pull request by pmconrad**
Mostly compiler warnings / issues detected by static code analysis.
Had to adapt some unit tests because testnet uses different defaults (MCR/MSSR, core symbol name). All tests in chain_test should work now on both develop and testnet (except for the known something-for-nothing bug).

### CODE REVIEW

**Comment by oxarbitrage** [comment]
nice work. code changes look ok with me, compilation works (with less warnings), replayed fine from start to now, test cases as you mention are only failing at the 5 cases added at https://github.com/bitshares/bitshares-core/pull/345
merging the pull.

**Comment by xeroc** [comment]
On my API node, I am getting lots of these messages:

```
   63.1208%   6880000 of 10899729   
1334838ms th_a       db_maint.cpp:253              update_active_commit ] Different stake targets: 33416853560229 / 451625218383678
1334838ms th_a       db_maint.cpp:272              update_active_commit ] Committee member count mismatch 3 / 5
1336242ms th_a       db_maint.cpp:253              update_active_commit ] Different stake targets: 33416853056154 / 451625219974494
1336242ms th_a       db_maint.cpp:272              update_active_commit ] Committee member count mismatch 3 / 5
1337532ms th_a       db_maint.cpp:253              update_active_commit ] Different stake targets: 33416852978108 / 451625220616782
1337532ms th_a       db_maint.cpp:272              update_active_commit ] Committee member count mismatch 3 / 5
1338788ms th_a       db_maint.cpp:253              update_active_commit ] Different stake targets: 33416852875787 / 451625220784017
1338788ms th_a       db_maint.cpp:272              update_active_commit ] Committee member count mismatch 3 / 5
1340053ms th_a       db_maint.cpp:253              update_active_commit ] Different stake targets: 33416853139289 / 451624221483925
1340053ms th_a       db_maint.cpp:272              update_active_commit ] Committee member count mismatch 3 / 5
1341293ms th_a       db_maint.cpp:253              update_active_commit ] Different stake targets: 33416853246285 / 451624223034372
1341293ms th_a       db_maint.cpp:272              update_active_commit ] Committee member count mismatch 3 / 5
1342614ms th_a       db_maint.cpp:253              update_active_commit ] Different stake targets: 33416853255583 / 451624224393614
1342614ms th_a       db_maint.cpp:272              update_active_commit ] Committee member count mismatch 3 / 5
1343971ms th_a       db_maint.cpp:253              update_active_commit ] Different stake targets: 33416853392252 / 451624225180712
1343971ms th_a       db_maint.cpp:272              update_active_commit ] Committee member count mismatch 3 / 5
1345136ms th_a       db_maint.cpp:253              update_active_commit ] Different stake targets: 33416853796525 / 451624226766728
1345136ms th_a       db_maint.cpp:272              update_active_commit ] Committee member count mismatch 3 / 5
```
.. during replay.

What's causing this?

**Comment by oxarbitrage** [comment]
this is caused by hardfork pull request at: https://github.com/bitshares/bitshares-core/pull/369

log message will be removed after the hardfork date pass.

**Comment by xeroc** [comment]
Oh, I totally missed that fix. Thanks for pointing it out!

**Pull request merged**
