### PR TITLE
Added login_api::get_server_information (Issue #626)

### PR DESCRIPTION
**Pull request by jmjatlanta**
This function returns an fc::mutable_variant_object that contains the following keys:
server_version
server_sha_version
server_version_timestamp
ssl_version
boost_version
websocket_version

fc::mutable_variant_object was used as it seemed to fit with other similar functions.

### CODE REVIEW

**Comment by oxarbitrage** [comment]
hi there John, i think it can be some confusion with the ticket name at https://github.com/bitshares/bitshares-core/issues/626.

The output on this pull is more for a node owner, owner can use `--version` of `witness_node` binary to get this data.

What is needed is api related configuration from the config file. github version is good so a client can know if a feature is present in the api but ssl, boost and such is not needed.

api version is a constant.
from the configuration, activated plugins, bucket-size, etc will be good data to expose.

**Comment by jmjatlanta** [comment]
@oxarbitrage Thanks for the comments. I am changing my implementation per your notes. When you say "api version is a constant" are you referring to "GRAPHENE_CURRENT_DB_VERSION" or something else?

Also, while I make these changes, should I close this PR and create a new one later, or just add to this one?

**Comment by oxarbitrage** [comment]
hi @jmjatlanta lets keep the work in this pull request if possible. sometimes, if the pull stays for too long without a merge it can start to have conflicts against the `develop` branch so in that case we can open a new one or if a change is so big that it will be clearer in a new pull. 
by now this pull will make it.

i am going to test it up and let you know more, i like to have a place for cli wallet tests, going good so far. thanks.

GRAPHENE_CURRENT_DB_VERSION yes, i saw you added it, its needed, ill send you some more ideas of what else will be good to show.

i am unsure if need to be logged to make this call or just adding to `database_api` will be fine. what do you think @abitmore ?

**Comment by jmjatlanta** [comment]
I implemented a method to get the options for each plugin. The application can then iterate the plugins and retrieve the options for each.

See market_history_plugin.cpp->plugin_get_options to see how I envision it to be implemented.
See api.cpp->login_api->get_server_information to see the method that gathers the information
See tests/cli/main.cpp to see an example of its usage and output.

**Comment by pmconrad** [comment]
I think this API is a security risk. Please add an option to explicitly enable it, and disable by default.

**Comment by oxarbitrage** [comment]
what if we make it more simple and add a call `get_api_version` that returns `GRAPHENE_CURRENT_DB_VERSION` and nothing more ?

**Comment by ryanRfox** [comment]
It's not clear to me if changes to API must be in Protocol Upgrade only, or can be in Feature Release. @jmjatlanta @oxarbitrage please Label #626 and place it on the proper project board along with this PR. Thanks

**Comment by oxarbitrage** [comment]
this is not protocol upgrade, it is just paused because expose this data in remote can be considered a security issue. solution i think will be have this feature as optional and disabled by default or not do it.

**Comment by ryanRfox** [comment]
Please continue solution discussion within the #626

**Comment by jmjatlanta** [comment]
Once again, merging in changes from base branch did not go as planned. I will try to salvage this PR with another commit.

**Comment by jmjatlanta** [comment]
Provided a cleaner implementation in https://github.com/bitshares/bitshares-core/pull/1070

**Pull request closed without merging**
