### PR TITLE
Add g++ to readme for building on Ubuntu 16.04

### PR DESCRIPTION
**Pull request by abitmore**

### CODE REVIEW

**Comment by abitmore** [comment]
Better to install `doxygen` and `libreadline-dev` as well

**Comment by oxarbitrage** [comment]
please note there is a more detailed file to install in ubuntu(https://github.com/bitshares/bitshares-core/wiki/BUILD_UBUNTU) where it describes how to install boost manually. inside that section there is g++:

`sudo apt-get install autotools-dev build-essential g++ libbz2-dev libicu-dev python-dev`

i always install boost manually however if boost is already installed and g++ still needed then i agree with your change. 

let me know if this is the case.

**Comment by abitmore** [comment]
G++ is needed for building `bitshares-core` on my new AWS Ubuntu16.04 instance, where distro-shipped libboost-dev-all 1.58 package has been installed already. Without it, `cmake` fails.

**Comment by abitmore** [comment]
Forgot to mention, my new instance was for testnet.

**Comment by oxarbitrage** [comment]
merged.

**Pull request merged**
