### PR TITLE
get_key_references should not subscribe to related accounts (Issue 1472)

### LINKED ISSUE #1472: get_key_references performance issue?
**Bug Description**
If a key is in authorities of many accounts, `get_key_references` API will return all of them <del>and will subscribe to all of them</del>, this could lead to potential performance issues. This API is used by GUI to get related accounts when importing a key.

https://github.com/bitshares/bitshares-ui/issues/2367 is related.

Update:
due to a bug, (I believe) the API is not subscribing to the returned accounts, so we can
- [ ] completely remove the code about subscribing to accounts

The result can still be too large, E.G. containing thousands of accounts, thus can be problematic.
- [ ] cap size of returned data?

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [x] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

### PR DESCRIPTION
**Pull request by jmjatlanta**
Fixes #1472

### CODE REVIEW

**Comment by abitmore** [comment]
I agree with @pmconrad. Likely clients will call `get_full_accounts` or similar after calling this.

**Comment by jmjatlanta** [comment]
get_key_references no longer subscribes to associated accounts, although it still subscribes to the passed-in keys.

#1472 mentions limiting the size of final_results. Should that be an arbitrary number? Should it be configurable? Perhaps it should be done under another issue (more discussion needed)?

**Comment by pmconrad** [comment]
IMO you could limit the size of the incoming vector to a fixed value. Making this configurable is part of #782 / #1478.
Adding limits to the output would also require start and limit parameters, which breaks compatibility. IMO the performance impact is limited anyway.

**Comment by jmjatlanta** [comment]
> IMO you could limit the size of the incoming vector to a fixed value. Making this configurable is part of #782 / #1478.

I interpret the above as "set the max limit of the incoming vector to 100 items, and ask manikey123 to make the 100 configurable. Do nothing to limit the size of the returned vector." Is that the correct interpretation?

**Pull request merged**
