### PR TITLE
Fix sign_memo command for signing with public keys

### PR DESCRIPTION
**Pull request by abitmore**
Fix sign_memo command for signing with public keys, and add CLI tests
- more tests about read_memo and sign_memo
- formatter of account_update_operation in account history
- result formatter for SHA256 hashes in HTLC operations

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
What can we do with this (from user's viewpoint) that we could not do before?

**Comment by abitmore** [comment]
@sschiessl-bcp the existing feature makes it possible that memo to be readable by a 3rd party but not the recipient, by using a key the 3rd party provided, although the use case is not obvious. Before the changes offered in this pull request, the user need to add the key to `cli_wallet` with a label, then run the command with that label. After the change, the user can run the command with the key directly.

**Comment by sschiessl-bcp** [comment]
What would be a use case? Auditing?

**Comment by abitmore** [comment]
TBH I don't know. The feature is already there for a long time.
One use case I think is when the recipient doesn't have a valid memo key, the sender can still send the funds with a memo, and the memo is perhaps useful for the sender, e.g. for tracking.

**Pull request merged**
