### PR TITLE
adding notify-all option to account history plugin

### PR DESCRIPTION
**Pull request by oxarbitrage**
how do we test if it is working ?

For issue #265 (and more discussions are there).

### CODE REVIEW

**Comment by abitmore** [comment]
The implementation looks fine. However I think the parameter name `notify-all` is too generic.

For testing, create accounts with/without referrer, with/without data in `account_auths`, run `witness_node` with/without the new parameter, results of `get_relative_account_history` API on the referrer and/or multi-sig accounts should be different.

**Comment by oxarbitrage** [comment]
ok got it. currently traveling, ill make the tests as you describe as soon as i get back tuesday-wednesday. if you have ideas for parameter name please let me know.

**Comment by abitmore** [comment]
@cogutvalera your comment didn't help, but rather annoying. This PR is labeled "discussion needed", why not add your thoughts? Although IMHO this is low priority.

**Comment by cogutvalera** [comment]
just want to know the status of this issue, can I claim it later or @oxarbitrage will do it ?

**Comment by cogutvalera** [comment]
sorry if I didn't choose right words and if they are really annoying ! I will remove them now ! Sorry @oxarbitrage @abitmore really sorry ! My fault ! Just want to know the status of this issue because it is old issue as I can see and maybe a bit later I will can claim this issue if possible or will help to @oxarbitrage

**Comment by abitmore** [comment]
Lately I think it's better to fix the issue in a consensus-upgrade style, although strictly it's not a consensus change, because many 3rd-party applications rely on consistent numbering in account history. That said, only track all related accounts (for newly created accounts) after a defined time.

**Pull request closed without merging**
