### PR TITLE
update default buckets.

### PR DESCRIPTION
**Pull request by oxarbitrage**
https://github.com/bitshares/bitshares-core/issues/465

pull updates default buckets to something more standard with charting applications(1 min, 5 mins, 15 mins, 30 mins, 1 h, 4h and 1 day)

### CODE REVIEW

**Comment by abitmore** [comment]
Need to add 30m as well? It's in the new code.

**Comment by oxarbitrage** [comment]
I think 30mins is pretty standard. Will be requested eventually.

**Comment by abitmore** [comment]
Make a test to see how much more RAM is needed for the new buckets? I guess around 300M with current chain.

**Comment by oxarbitrage** [comment]
yea, well, 5 buckets in current default tracking 1000 entires for each by default too. 
we are removing one(15 seconds) and adding 3(15 mins   - 30 mins - 4 hs). this should be an increase of 40% but i can get more exact numbers if i sync 2 chains. will do it tomorrow.

**Comment by oxarbitrage** [comment]
i made a test today loading `witness_node` and `market_history` plugins(no account history data).
in the first sync with default values:

`bucket-size = [15,60,300,3600,86400]`

ram was: 4912548K after sync.

in a second ram with the new bucket numbers:

`bucket-size = [60,300,900,1800,3600,14400,86400]`

ram was: 4854132K

this was actually a surprise to me that the removal of the 15 seconds buckets reduced ram usage even if more bucket sizes were added.

a new try with this setup:

`bucket-size = [15,60,300,900,1800,3600,14400,86400]`

ram: 5137128K

what i think is happening is that new markets don't have enough data to fill the big buckets while pretty much all will fill the 15 seconds 1000 bucket size.

**Pull request merged**
