### PR TITLE
Asset API Added 2 functions

### PR DESCRIPTION
**Pull request by oxarbitrage**

### CODE REVIEW

**Comment by oxarbitrage** [comment]
some output of the new calls:

1- get_asset_holders_count

`> {"id":1, "method":"call", "params":[2,"get_asset_holders_count",["1.3.0"]]}
< {"id":1,"result":825}`

2- get_all_asset_holders

`> {"id":1, "method":"call", "params":[2,"get_all_asset_holders", []]}

< {"id":1,"result":[{"asset_id":"1.3.0","count":862},{"asset_id":"1.3.100","count":-1},{"asset_id":"1.3.101","count":-1},{"asset_id":"1.3.102","count":2},{"asset_id":"1.3.103","count":50},{"asset_id":"1.3.104","count":-1},{"asset_id":"1.3.105","count":20},{"asset_id":"1.3.106","count":37},{"asset_id":"1.3.107","count":-1},{"asset_id":"1.3.108","count":-1},{"asset_id":"1.3.109","count":-1},{"asset_id":"1.3.110","count":-1},{"asset_id":"1.3.111","count":0},{"asset_id":"1.3.112","count":-1},{"asset_id":"1.3.113","count":116},{"asset_id":"1.3.114","count":-1},{"asset_id":"1.3.115","count":0},{"asset_id":"1.3.116","count":1},{"asset_id":"1.3.117","count":-1},{"asset_id":"1.3.118","count":0},{"asset_id":"1.3.119","count":0},{"asset_id":"1.3.120","count":14},{"asset_id":"1.3.121","count":268},{"asset_id":"1.3.122","count":0},{"asset_id":"1.3.123","count":-1},{"asset_id":"1.3.124","count":-1},{"asset_id":"1.3.125","count":-1},{"asset_id":"1.3.126","count":-1},{"asset_id":"1.3.127","count":10},{"asset_id":"1.3.128","count":-1},{"asset_id":"1.3.129","count":-1},{"asset_id":"1.3.130","count":6},{"asset_id":"1.3.131","count":-1},{"asset_id":"1.3.132","count":-1},{"asset_id":"1.3.133","count":-1},{"asset_id":"1.3.134","count":-1},{"asset_id":"1.3.135","count":-1},{"asset_id":"1.3.136","count":26},{"asset_id":"1.3.137","count":-1},{"asset_id":"1.3.138","count":22},{"asset_id":"1.3.139","count":-1},{"asset_id":"1.3.140","count":13},{"asset_id":"1.3.141","count":-1},{"asset_id":"1.3.142","count":4},{"asset_id":"1.3.143","count":-1},{"asset_id":"1.3.144","count":-1},{"asset_id":"1.3.145","count":-1},{"asset_id":"1.3.146","count":-1},{"asset_id":"1.3.147","count":-1},{"asset_id":"1.3.148","count":-1},{"asset_id":"1.3.149","count":-1},{"asset_id":"1.3.150","count":-1},{"asset_id":"1.3.151","count":-1},{"asset_id":"1.3.152","count":-1},{"asset_id":"1.3.153","count":-1},{"asset_id":"1.3.154","count":-1},{"asset_id":"1.3.155","count":-1},{"asset_id":"1.3.156","count":-1},{"asset_id":"1.3.157","count":0},{"asset_id":"1.3.158","count":14},{"asset_id":"1.3.159","count":-1},{"asset_id":"1.3.160","count":-1},{"asset_id":"1.3.161","count":-1},{"asset_id":"1.3.162","count":-1},{"asset_id":"1.3.163","count":-1},{"asset_id":"1.3.164","count":-1},{"asset_id":"1.3.165","count":-1},{"asset_id":"1.3.166","count":-1},{"asset_id":"1.3.167","count":-1},{"asset_id":"1.3.168","count":-1},{"asset_id":"1.3.169","count":-1},{"asset_id":"1.3.170","count":-1},{"asset_id":"1.3.171","count":-1},{"asset_id":"1.3.172","count":10},{"asset_id":"1.3.173","count":-1},{"asset_id":"1.3.174","count":-1},{"asset_id":"1.3.175","count":0},{"asset_id":"1.3.176","count":-1},{"asset_id":"1.3.177","count":-1},{"asset_id":"1.3.178","count":-1},{"asset_id":"1.3.179","count":0},{"asset_id":"1.3.180","count":0},{"asset_id":"1.3.181","count":-1},{"asset_id":"1.3.182","count":-1},{"asset_id":"1.3.183","count":-1},{"asset_id":"1.3.184","count":-1},{"asset_id":"1.3.185","count":-1},{"asset_id":"1.3.186","count":-1},{"asset_id":"1.3.187","count":-1},{"asset_id":"1.3.188","count":-1},{"asset_id":"1.3.189","count":-1},{"asset_id":"1.3.190","count":-1},{"asset_id":"1.3.191","count":-1},{"asset_id":"1.3.192","count":-1},{"asset_id":"1.3.193","count":-1},{"asset_id":"1.3.194","count":0},{"asset_id":"1.3.195","count":-1},{"asset_id":"1.3.196","count":-1},{"asset_id":"1.3.197","count":-1},{"asset_id":"1.3.198","count":-1},{"asset_id":"1.3.199","count":-1},{"asset_id":"1.3.200","count":-1},{"asset_id":"1.3.201","count":-1},{"asset_id":"1.3.202","count":-1},{"asset_id":"1.3.203","count":0},{"asset_id":"1.3.204","count":-1},{"asset_id":"1.3.205","count":-1},{"asset_id":"1.3.206","count":-1},{"asset_id":"1.3.207","count":-1},{"asset_id":"1.3.208","count":-1},{"asset_id":"1.3.209","count":-1},{"asset_id":"1.3.210","count":-1},{"asset_id":"1.3.211","count":-1},{"asset_id":"1.3.212","count":-1},{"asset_id":"1.3.213","count":0},{"asset_id":"1.3.214","count":-1},{"asset_id":"1.3.215","count":-1},{"asset_id":"1.3.216","count":-1},{"asset_id":"1.3.217","count":-1},{"asset_id":"1.3.218","count":-1},{"asset_id":"1.3.219","count":-1},{"asset_id":"1.3.220","count":-1},{"asset_id":"1.3.221","count":-1},{"asset_id":"1.3.222","count":-1},{"asset_id":"1.3.223","count":-1},{"asset_id":"1.3.224","count":-1},{"asset_id":"1.3.225","count":-1},{"asset_id":"1.3.226","count":-1},{"asset_id":"1.3.227","count":-1},{"asset_id":"1.3.228","count":-1},{"asset_id":"1.3.229","count":-1},{"asset_id":"1.3.230","count":-1},{"asset_id":"1.3.231","count":-1},{"asset_id":"1.3.232","count":-1},{"asset_id":"1.3.233","count":-1},{"asset_id":"1.3.234","count":-1},{"asset_id":"1.3.235","count":-1},{"asset_id":"1.3.236","count":-1},{"asset_id":"1.3.237","count":-1},{"asset_id":"1.3.238","count":-1},{"asset_id":"1.3.239","count":-1},{"asset_id":"1.3.240","count":0},{"asset_id":"1.3.241","count":6},{"asset_id":"1.3.242","count":-1},{"asset_id":"1.3.243","count":0},{"asset_id":"1.3.244","count":-1},{"asset_id":"1.3.245","count":-1},{"asset_id":"1.3.246","count":-1},{"asset_id":"1.3.247","count":-1},{"asset_id":"1.3.248","count":3},{"asset_id":"1.3.249","count":-1},{"asset_id":"1.3.250","count":-1},{"asset_id":"1.3.251","count":3},{"asset_id":"1.3.252","count":0},{"asset_id":"1.3.253","count":-1},{"asset_id":"1.3.254","count":1},{"asset_id":"1.3.255","count":0},{"asset_id":"1.3.256","count":0},{"asset_id":"1.3.257","count":0},{"asset_id":"1.3.258","count":-1},{"asset_id":"1.3.259","count":-1},{"asset_id":"1.3.260","count":-1},{"asset_id":"1.3.261","count":-1},{"asset_id":"1.3.262","count":-1},{"asset_id":"1.3.263","count":-1},{"asset_id":"1.3.264","count":-1},{"asset_id":"1.3.265","count":-1},{"asset_id":"1.3.266","count":0},{"asset_id":"1.3.267","count":-1},{"asset_id":"1.3.268","count":-1},{"asset_id":"1.3.269","count":-1},{"asset_id":"1.3.270","count":-1},{"asset_id":"1.3.271","count":-1},{"asset_id":"1.3.272","count":-1},{"asset_id":"1.3.273","count":1},{"asset_id":"1.3.274","count":-1},{"asset_id":"1.3.275","count":-1},{"asset_id":"1.3.276","count":2},{"asset_id":"1.3.277","count":-1},{"asset_id":"1.3.278","count":-1},{"asset_id":"1.3.279","count":-1},{"asset_id":"1.3.280","count":0},{"asset_id":"1.3.281","count":0},{"asset_id":"1.3.282","count":-1},{"asset_id":"1.3.283","count":-1},{"asset_id":"1.3.284","count":0},{"asset_id":"1.3.285","count":-1},{"asset_id":"1.3.286","count":-1},{"asset_id":"1.3.287","count":-1},{"asset_id":"1.3.288","count":-1},{"asset_id":"1.3.289","count":3},{"asset_id":"1.3.290","count":4},{"asset_id":"1.3.291","count":-1},{"asset_id":"1.3.292","count":-1},{"asset_id":"1.3.293","count":-1},{"asset_id":"1.3.294","count":-1},{"asset_id":"1.3.295","count":-1},{"asset_id":"1.3.296","count":-1},{"asset_id":"1.3.297","count":-1},{"asset_id":"1.3.298","count":-1},{"asset_id":"1.3.299","count":-1},{"asset_id":"1.3.300","count":4},{"asset_id":"1.3.301","count":-1},{"asset_id":"1.3.302","count":-1},{"asset_id":"1.3.303","count":4},{"asset_id":"1.3.304","count":-1},{"asset_id":"1.3.305","count":-1},{"asset_id":"1.3.306","count":0},{"asset_id":"1.3.307","count":0},{"asset_id":"1.3.308","count":0},{"asset_id":"1.3.309","count":-1},{"asset_id":"1.3.310","count":-1},{"asset_id":"1.3.311","count":-1},{"asset_id":"1.3.312","count":-1},{"asset_id":"1.3.313","count":-1},{"asset_id":"1.3.314","count":-1},{"asset_id":"1.3.315","count":-1},{"asset_id":"1.3.316","count":-1},{"asset_id":"1.3.317","count":-1},{"asset_id":"1.3.318","count":-1},{"asset_id":"1.3.319","count":-1},{"asset_id":"1.3.320","count":0},{"asset_id":"1.3.321","count":-1},{"asset_id":"1.3.322","count":-1},{"asset_id":"1.3.323","count":0},{"asset_id":"1.3.324","count":-1},{"asset_id":"1.3.325","count":4},{"asset_id":"1.3.326","count":-1},{"asset_id":"1.3.327","count":0},{"asset_id":"1.3.328","count":0},{"asset_id":"1.3.329","count":0},{"asset_id":"1.3.330","count":-1},{"asset_id":"1.3.331","count":0},{"asset_id":"1.3.332","count":0},{"asset_id":"1.3.333","count":-1},{"asset_id":"1.3.334","count":23},{"asset_id":"1.3.335","count":-1},{"asset_id":"1.3.336","count":-1},{"asset_id":"1.3.337","count":-1},{"asset_id":"1.3.338","count":5},{"asset_id":"1.3.339","count":-1},{"asset_id":"1.3.340","count":-1},{"asset_id":"1.3.341","count":-1},{"asset_id":"1.3.342","count":14},{"asset_id":"1.3.343","count":-1},{"asset_id":"1.3.344","count":0},{"asset_id":"1.3.345","count":0},{"asset_id":"1.3.346","count":-1},{"asset_id":"1.3.347","count":-1},{"asset_id":"1.3.348","count":-1},{"asset_id":"1.3.349","count":2},{"asset_id":"1.3.350","count":11},{"asset_id":"1.3.351","count":-1},{"asset_id":"1.3.352","count":-1},{"asset_id":"1.3.353","count":-1},{"asset_id":"1.3.354","count":-1},{"asset_id":"1.3.355","count":-1},{"asset_id":"1.3.356","count":-1},{"asset_id":"1.3.357","count":-1},{"asset_id":"1.3.358","count":-1},{"asset_id":"1.3.359","count":-1},{"asset_id":"1.3.360","count":2},{"asset_id":"1.3.361","count":-1},{"asset_id":"1.3.362","count":4},{"asset_id":"1.3.363","count":-1},{"asset_id":"1.3.364","count":-1},{"asset_id":"1.3.365","count":-1},{"asset_id":"1.3.366","count":0},{"asset_id":"1.3.367","count":0},{"asset_id":"1.3.368","count":-1},{"asset_id":"1.3.369","count":12},{"asset_id":"1.3.370","count":-1},{"asset_id":"1.3.371","count":-1},{"asset_id":"1.3.372","count":-1},{"asset_id":"1.3.373","count":-1},{"asset_id":"1.3.374","count":-1},{"asset_id":"1.3.375","count":-1},{"asset_id":"1.3.376","count":-1},{"asset_id":"1.3.377","count":2},{"asset_id":"1.3.378","count":-1},{"asset_id":"1.3.379","count":-1},{"asset_id":"1.3.380","count":-1},{"asset_id":"1.3.381","count":-1},{"asset_id":"1.3.382","count":-1},{"asset_id":"1.3.383","count":-1},{"asset_id":"1.3.384","count":-1},{"asset_id":"1.3.385","count":-1},{"asset_id":"1.3.386","count":-1},{"asset_id":"1.3.387","count":-1},{"asset_id":"1.3.388","count":-1},{"asset_id":"1.3.389","count":-1},{"asset_id":"1.3.390","count":-1},{"asset_id":"1.3.391","count":-1},{"asset_id":"1.3.392","count":-1},{"asset_id":"1.3.393","count":-1},{"asset_id":"1.3.394","count":-1},{"asset_id":"1.3.395","count":-1},{"asset_id":"1.3.396","count":-1},{"asset_id":"1.3.397","count":5},{"asset_id":"1.3.398","count":-1},{"asset_id":"1.3.399","count":-1},{"asset_id":"1.3.400","count":-1},{"asset_id":"1.3.401","count":-1},{"asset_id":"1.3.402","count":-1},{"asset_id":"1.3.403","count":-1},{"asset_id":"1.3.404","count":-1},{"asset_id":"1.3.405","count":-1},{"asset_id":"1.3.406","count":-1},{"asset_id":"1.3.407","count":-1},{"asset_id":"1.3.408","count":-1},{"asset_id":"1.3.409","count":-1},{"asset_id":"1.3.410","count":-1},{"asset_id":"1.3.411","count":-1},{"asset_id":"1.3.412","count":-1},{"asset_id":"1.3.413","count":-1},{"asset_id":"1.3.414","count":-1},{"asset_id":"1.3.415","count":-1},{"asset_id":"1.3.416","count":-1},{"asset_id":"1.3.417","count":-1},{"asset_id":"1.3.418","count":15},{"asset_id":"1.3.419","count":0},{"asset_id":"1.3.420","count":0},{"asset_id":"1.3.421","count":-1},{"asset_id":"1.3.422","count":6},{"asset_id":"1.3.423","count":-1},{"asset_id":"1.3.424","count":-1},{"asset_id":"1.3.425","count":-1},{"asset_id":"1.3.426","count":-1},{"asset_id":"1.3.427","count":-1},{"asset_id":"1.3.428","count":4},{"asset_id":"1.3.429","count":-1},{"asset_id":"1.3.430","count":-1},{"asset_id":"1.3.431","count":0},{"asset_id":"1.3.432","count":22},{"asset_id":"1.3.433","count":-1},{"asset_id":"1.3.434","count":-1},{"asset_id":"1.3.435","count":-1},{"asset_id":"1.3.436","count":-1},{"asset_id":"1.3.437","count":-1},{"asset_id":"1.3.438","count":-1},{"asset_id":"1.3.439","count":-1},{"asset_id":"1.3.440","count":-1},{"asset_id":"1.3.441","count":-1},{"asset_id":"1.3.442","count":0},{"asset_id":"1.3.443","count":-1},{"asset_id":"1.3.444","count":-1},{"asset_id":"1.3.445","count":-1},{"asset_id":"1.3.446","count":-1},{"asset_id":"1.3.447","count":0},{"asset_id":"1.3.448","count":-1},{"asset_id":"1.3.449","count":-1},{"asset_id":"1.3.450","count":0},{"asset_id":"1.3.451","count":-1},{"asset_id":"1.3.452","count":-1},{"asset_id":"1.3.453","count":-1},{"asset_id":"1.3.454","count":-1},{"asset_id":"1.3.455","count":-1},{"asset_id":"1.3.456","count":-1},{"asset_id":"1.3.457","count":-1},{"asset_id":"1.3.458","count":-1},{"asset_id":"1.3.459","count":-1},{"asset_id":"1.3.460","count":-1},{"asset_id":"1.3.461","count":-1},{"asset_id":"1.3.462","count":-1},{"asset_id":"1.3.463","count":-1},{"asset_id":"1.3.464","count":-1},{"asset_id":"1.3.465","count":-1},{"asset_id":"1.3.466","count":0},{"asset_id":"1.3.467","count":-1},{"asset_id":"1.3.468","count":-1},{"asset_id":"1.3.469","count":-1},{"asset_id":"1.3.470","count":-1},{"asset_id":"1.3.471","count":-1},{"asset_id":"1.3.472","count":-1},{"asset_id":"1.3.473","count":2},{"asset_id":"1.3.474","count":-1},{"asset_id":"1.3.475","count":-1},{"asset_id":"1.3.476","count":0},{"asset_id":"1.3.477","count":-1},{"asset_id":"1.3.478","count":-1},{"asset_id":"1.3.479","count":-1},{"asset_id":"1.3.480","count":-1},{"asset_id":"1.3.481","count":-1},{"asset_id":"1.3.482","count":-1},{"asset_id":"1.3.483","count":-1},{"asset_id":"1.3.484","count":-1},{"asset_id":"1.3.485","count":-1},{"asset_id":"1.3.486","count":-1},{"asset_id":"1.3.487","count":-1},{"asset_id":"1.3.488","count":-1},{"asset_id":"1.3.489","count":-1},{"asset_id":"1.3.490","count":-1},{"asset_id":"1.3.491","count":-1},{"asset_id":"1.3.492","count":-1},{"asset_id":"1.3.493","count":-1},{"asset_id":"1.3.494","count":-1},{"asset_id":"1.3.495","count":-1},{"asset_id":"1.3.496","count":-1},{"asset_id":"1.3.497","count":-1},{"asset_id":"1.3.498","count":-1},{"asset_id":"1.3.499","count":-1},{"asset_id":"1.3.500","count":-1},{"asset_id":"1.3.501","count":-1},{"asset_id":"1.3.502","count":-1},{"asset_id":"1.3.503","count":-1},{"asset_id":"1.3.504","count":-1},{"asset_id":"1.3.505","count":-1},{"asset_id":"1.3.506","count":-1},{"asset_id":"1.3.507","count":-1},{"asset_id":"1.3.508","count":-1},{"asset_id":"1.3.509","count":-1},{"asset_id":"1.3.510","count":-1},{"asset_id":"1.3.511","count":-1},{"asset_id":"1.3.512","count":-1},{"asset_id":"1.3.513","count":-1},{"asset_id":"1.3.514","count":-1},{"asset_id":"1.3.515","count":-1},{"asset_id":"1.3.516","count":-1},{"asset_id":"1.3.517","count":-1},{"asset_id":"1.3.518","count":-1},{"asset_id":"1.3.519","count":-1},{"asset_id":"1.3.520","count":-1},{"asset_id":"1.3.521","count":-1},{"asset_id":"1.3.522","count":-1},{"asset_id":"1.3.523","count":0},{"asset_id":"1.3.524","count":-1},{"asset_id":"1.3.525","count":-1},{"asset_id":"1.3.526","count":-1},{"asset_id":"1.3.527","count":-1},{"asset_id":"1.3.528","count":0},{"asset_id":"1.3.529","count":-1},{"asset_id":"1.3.530","count":1},{"asset_id":"1.3.531","count":-1},{"asset_id":"1.3.532","count":-1},{"asset_id":"1.3.533","count":-1},{"asset_id":"1.3.534","count":-1},{"asset_id":"1.3.535","count":71},{"asset_id":"1.3.536","count":-1},{"asset_id":"1.3.537","count":-1},{"asset_id":"1.3.538","count":3},{"asset_id":"1.3.539","count":28},{"asset_id":"1.3.540","count":-1},{"asset_id":"1.3.541","count":2},{"asset_id":"1.3.542","count":-1},{"asset_id":"1.3.543","count":-1},{"asset_id":"1.3.544","count":3},{"asset_id":"1.3.545","count":-1},{"asset_id":"1.3.546","count":-1},{"asset_id":"1.3.547","count":-1},{"asset_id":"1.3.548","count":-1},{"asset_id":"1.3.549","count":-1},{"asset_id":"1.3.550","count":-1},{"asset_id":"1.3.551","count":0},{"asset_id":"1.3.552","count":2},{"asset_id":"1.3.553","count":-1},{"asset_id":"1.3.554","count":-1},{"asset_id":"1.3.555","count":-1}]}
`

need to be logged in to call asset_api functions.

**Comment by vikramrajkumar** [comment]
@oxarbitrage It looks like this includes an accidental reversion of the fc submodule version.

**Comment by oxarbitrage** [comment]
@vikramrajkumar i am not sure how that happened but it seems to me that the reversion actually do nothing or at least i can't find here in github the code difference. it also says "Submodule fc updated 0 files".

**Comment by vikramrajkumar** [comment]
GitHub is not clearly showing it but it seems to revert `libraries/fc` back to commit c1361d8cf97de719b6fd0ece244b3ae51d472e3e (shown in https://github.com/oxarbitrage/bitshares-core/tree/new-functions-asset-api/libraries) instead of e3238628fc319fbd9ce8d3b00e771cb806d69f2e in current bitshares-core master. Make sure your local repo has the updated fc checked out and amend this PR.

**Comment by oxarbitrage** [comment]
@vikramrajkumar please check now, the reversion of the fc is gone and the file changes are only 2 now. thanks again.

**Pull request merged**
