### PR TITLE
Merge release to master for 3.1.0

### PR DESCRIPTION
**Pull request by abitmore**
See #1745 for release notes.

### CODE REVIEW

**Comment by jmjatlanta** [comment]
The snapshot has a lot of differences. I am attempting to sort through them.

https://gist.github.com/jmjatlanta/8fb91043d7ce1b30b718c93e28754258

The first 290 lines are due to the addition of fail_reason, which is fine. The rest I am attempting to diagnose the cause.

**Comment by abitmore** [comment]
@jmjatlanta what block numbers did you use for the snapshots? Both fully replayed, or one of them was generated while syncing? That may be the cause of the differences, because `2.7.x ` objects are `impl_transaction_object_type` objects which are for "dedupe" which is disabled while replaying.

**Comment by jmjatlanta** [comment]
> @jmjatlanta what block numbers did you use for the snapshots? Both fully replayed, or one of them was generated while syncing? That may be the cause of the differences, because `2.7.x ` objects are `impl_transaction_object_type` objects which are for "dedupe" which is disabled while replaying.

That's probably the issue. I picked a very recent block, which probably did some syncing on the first run. I am re-running the first run.

**Comment by jmjatlanta** [comment]
Unfortunately, while improved, the diff still contains many transactions that are different. Researching...

Here is the diff: https://gist.github.com/jmjatlanta/14c0376c2c0b7b2c9e2a32b7a782918f

**Comment by abitmore** [comment]
@jmjatlanta `transaction_index` for dedupe is enabled from `head_block - 10000`. please make sure that your data base for replay is the same.

**Comment by jmjatlanta** [comment]
> @jmjatlanta `transaction_index` for dedupe is enabled from `head_block - 50`. please make sure that your data base for replay is the same.

I am not sure what you mean. Would you provide more information? I am using the same database on each run. I am running the snapshot of the `release` branch and comparing it to the `master` branch.

**Comment by jmjatlanta** [comment]
It looks to me as if many (but not all) simply have a different database id. For instance, here are the first few lines of the file, matched by their data, not their id...

|old version|new version|
|---|---|
|2.7.5783|none|
|2.7.8013|none|
|2.7.48413|none|
|2.7.131993|none|
|2.7.131993|2.7.43939|
|135358|2.7.47304|
|2.7.149696|2.7.61642|

**Comment by abitmore** [comment]
Different IDs means the order they got inserted were different, or different number of transactions inserted before them then got removed. I didn't find why if both were replayed from the same data directory (aka same last_block_num thus same block number that enabled undo_do).

**Comment by abitmore** [comment]
About the differences on `2.7.x` objects:

https://github.com/bitshares/bitshares-core/blob/80a9f9f28aca648851dbe45b9eedb6b9f1adf704/libraries/chain/db_management.cpp#L94-L95

`last_block` would change if we let `witness_node` continue syncing after replay, so, on next replay, `skip_transaction_dupe_check` flag will be disabled on a later block which will lead to different results.

If we start witness_node with `--seed-nodes '[]'` parameter, it won't sync after replay, we'll get identical results on next replay.

Alternatively, if we take snapshots on a block older than `maximum_time_until_expiration`, then there will be no `2.7.x` object in snapshots, thus no difference.

**Pull request merged**
