### PR TITLE
Fix vote_id_type might be uninitialized #25

### PR DESCRIPTION
**Pull request by takaaki7**

### CODE REVIEW

**Comment by abitmore** [comment]
Good job. Best if we have a test case for it.

**Comment by oxarbitrage** [comment]
very nice @takaaki7 , i saw this issue open since a lot but i was not able to find a way to trigger it to test a fix. will be great if you can show a use case if you have. your contributions are more than welcome :)

**Comment by takaaki7** [comment]
I thought there is a test case. Sorry for hasty fix.
So just closing this PR or waiting until tests structure refactored are ok. (I can cooperate anyway :) )

**Comment by abitmore** [comment]
`vote_id_type` will be only initialized from a string when used in `account_create_operation` or `account_update_operation`. If it's uninitialized, the value will still be validated in `verify_account_votes(...)`, so won't cause trouble. I'm merging this PR. Other related issues will be discussed in another ticket.

**Pull request merged**
