### PR TITLE
replace BTS string literal with corresponding constant

### PR DESCRIPTION
**Pull request by ihla**

### CODE REVIEW

**Comment by oxarbitrage** [comment]
1 additional approve required to merge this changes.

**Comment by abitmore** [comment]
I think this change is wrong.

**Comment by oxarbitrage** [comment]
i tried this pull in a production chain and everything went fine.

**Comment by ihla** [comment]
my proposal was not addressing the code that is annotated as temporary in comments but the use of string literals instead of available defines, anyway i am fine with the solution if the temp code containing the literals were removed

**Comment by abitmore** [comment]
Those code are not for the BitShares production chain. IMHO they are related to new chains which are going to airdrop to BTS token holders (even BTS 0.x token holders), so they should recognize addresses / keys with a "BTS" prefix. Also useful for special test networks.

If we want to simply replace them with a macro without change the logic, we need to define another one but not use `GRAPHENE_SYMBOL` directly, although it's not easy for new comers to understand the difference.

**Comment by ihla** [comment]
I agree with @abitmore that current use of the mentioned string literals is confusing for new comers since it is not clear if they mean the same as the corresponding macros. The rectification would be helpful for us as we want to fork and change symbols.

**Comment by ihla** [comment]
I observe no movement in this issue for a while - @abitmore some hints on how to rectify this code are highly welcome.

**Comment by abitmore** [comment]
My suggestion: remove the temporary code, replay testnet and mainnet, to see whether they will break; or leave the code unchanged.

**Comment by pmconrad** [comment]
This PR is a mess. Please rebase your changes on latest develop and create a new PR.

**Comment by ihla** [comment]
continue as #665

**Pull request closed without merging**
