### PR TITLE
get_account_history_by_date

### PR DESCRIPTION
**Pull request by oxarbitrage**
### fuller_get_relative_account_history

for issue: https://github.com/bitshares/bitshares-core/issues/358

work in progress, need review.

currently, it is not possible to get user operation history by date, the main purpose of the call is to do that. Additionally it haves 2 filters requested at #358, this are market filter and operation type filter.

With the filters turned off the api will get operations(up to 100) inside date range period just as:

```
alfredo@alfredo-Inspiron-5559 ~/CLionProjects/issue358_2 $ curl --data '{"jsonrpc": "2.0", "params": ["history", "fuller_get_relative_account_history", ["1.2.356589", "2017-08-19T00:00:00", "2017-08-18T00:00:00", 100, false, "1.3.362", "1.3.0", false, 0]], "method": "call", "id": 10}' http://localhost:8090/rpc --silent  | jq
{
  "id": 10,
  "jsonrpc": "2.0",
  "result": [
    {
      "id": "1.11.59065461",
      "op": [
        1,
        {
          "fee": {
            "amount": 1213,
            "asset_id": "1.3.0"
          },
          "seller": "1.2.356589",
          "amount_to_sell": {
            "amount": 2390099989,
            "asset_id": "1.3.0"
          },
          "min_to_receive": {
            "amount": 32000000,
            "asset_id": "1.3.121"
          },
          "expiration": "2022-08-18T13:35:35",
          "fill_or_kill": false,
          "extensions": []
        }
      ],
      "result": [
        1,
        "1.7.23704013"
      ],
      "block_num": 19270508,
      "trx_in_block": 0,
      "op_in_trx": 0,
      "virtual_op": 27925
    },
    {
      "id": "1.11.58994869",
      "op": [
        22,
        {
          "fee": {
            "amount": 185414,
            "asset_id": "1.3.0"
          },
          "fee_paying_account": "1.2.152768",
          "expiration_time": "2017-08-19T13:35:58",
          "proposed_ops": [
            {
              "op": [
                1,
                {
                  "fee": {
                    "amount": 1213,
                    "asset_id": "1.3.0"
                  },
                  "seller": "1.2.356589",
                  "amount_to_sell": {
                    "amount": 2390099989,
                    "asset_id": "1.3.0"
                  },
                  "min_to_receive": {
                    "amount": 32000000,
                    "asset_id": "1.3.121"
                  },
                  "expiration": "2022-08-18T13:35:35",
                  "fill_or_kill": false,
                  "extensions": []
                }
              ]
            }
          ],
          "extensions": []
        }
      ],
      "result": [
        1,
        "1.10.4153"
      ],
      "block_num": 19265720,
      "trx_in_block": 4,
      "op_in_trx": 0,
      "virtual_op": 22868
    }
  ]
}
alfredo@alfredo-Inspiron-5559 ~/CLionProjects/issue358_2 $ 

```

by using the operation_type filter we can go after a specific operation type inside the interval juast as:

```
alfredo@alfredo-Inspiron-5559 ~/CLionProjects/issue358_2 $ curl --data '{"jsonrpc": "2.0", "params": ["history", "fuller_get_relative_account_history", ["1.2.356589", "2017-08-19T00:00:00", "2017-08-18T00:00:00", 100, false, "1.3.362", "1.3.0", true, 1]], "method": "call", "id": 10}' http://localhost:8090/rpc --silent  | jq
{
  "id": 10,
  "jsonrpc": "2.0",
  "result": [
    {
      "id": "1.11.59065461",
      "op": [
        1,
        {
          "fee": {
            "amount": 1213,
            "asset_id": "1.3.0"
          },
          "seller": "1.2.356589",
          "amount_to_sell": {
            "amount": 2390099989,
            "asset_id": "1.3.0"
          },
          "min_to_receive": {
            "amount": 32000000,
            "asset_id": "1.3.121"
          },
          "expiration": "2022-08-18T13:35:35",
          "fill_or_kill": false,
          "extensions": []
        }
      ],
      "result": [
        1,
        "1.7.23704013"
      ],
      "block_num": 19270508,
      "trx_in_block": 0,
      "op_in_trx": 0,
      "virtual_op": 27925
    }
  ]
}
alfredo@alfredo-Inspiron-5559 ~/CLionProjects/issue358_2 $ 
```

By using the market interval we can just get the market we are intersted in by:

```
alfredo@alfredo-Inspiron-5559 ~/CLionProjects/issue358_2 $ curl --data '{"jsonrpc": "2.0", "params": ["history", "fuller_get_relative_account_history", ["1.2.356589", "2017-08-19T00:00:00", "2017-08-18T00:00:00", 100, true, "1.3.362", "1.3.0", false, 1]], "method": "call", "id": 10}' http://localhost:8090/rpc --silent  | jq
{
  "id": 10,
  "jsonrpc": "2.0",
  "result": []
}
alfredo@alfredo-Inspiron-5559 ~/CLionProjects/issue358_2 $ curl --data '{"jsonrpc": "2.0", "params": ["history", "fuller_get_relative_account_history", ["1.2.356589", "2017-08-19T00:00:00", "2017-08-18T00:00:00", 100, true, "1.3.121", "1.3.0", false, 1]], "method": "call", "id": 10}' http://localhost:8090/rpc --silent  | jq
{
  "id": 10,
  "jsonrpc": "2.0",
  "result": [
    {
      "id": "1.11.59065461",
      "op": [
        1,
        {
          "fee": {
            "amount": 1213,
            "asset_id": "1.3.0"
          },
          "seller": "1.2.356589",
          "amount_to_sell": {
            "amount": 2390099989,
            "asset_id": "1.3.0"
          },
          "min_to_receive": {
            "amount": 32000000,
            "asset_id": "1.3.121"
          },
          "expiration": "2022-08-18T13:35:35",
          "fill_or_kill": false,
          "extensions": []
        }
      ],
      "result": [
        1,
        "1.7.23704013"
      ],
      "block_num": 19270508,
      "trx_in_block": 0,
      "op_in_trx": 0,
      "virtual_op": 27925
    }
  ]
}
alfredo@alfredo-Inspiron-5559 ~/CLionProjects/issue358_2 $ 
```

The market filter will look at the trading pair in 3 types of trading operations where we actually have a pair involved. this are `limit_order_create_operation`, `call_order_update_operation` and `fill_order_operation`

- need chain replay to work as the account_history_plugin need to save the dates of each op.
- to get more than 100 results the client need to pull the first 100, get the oldest date and make additional calls to the function changing the end date until the result size is less than 100. at this point the client will have all the history in the requested time range.

### CODE REVIEW

**Comment by xeroc** [comment]
Very useful call, but IMHO, it needs a better name :)
How about `get_account_history_by_date`?

**Comment by oxarbitrage** [comment]
yes, the name sucks, i actually changed it to `get_relative_account_history_bytime` in my local branch but i actually like your more so it will be `get_account_history_by_date`.

i am having some problems with making the indexing of the operations to work while i removed the asset one fully to make the call more generic. i will update and pull new code soon(in the next 1 or 2 days).

there is also an issue i am trying to solve we discussed in telegram with @abit with a `seconds_seq` addition as this will fail with accounts that can have more than 100 ops inside the same block and second). will keep you guys posted.

**Comment by oxarbitrage** [comment]
### get_account_history_by_date

Folks, i made some changes to this call, probably not definitive yet but getting closer i hope.

First, we have some new parameters, they are now:

```
          * @param account The account whose history should be queried
          * @param time_start Time to start
          * @param time_start Time to end
          * @param limit Maximum number of operations to retrieve (must not exceed 100)
          * @param seconds_seq Paging helper to browse more than @limit(100) ops in the same second
          * @param use_operation_filter Turn on filter by operation id
          * @param operation_type Operation type number to be used when use_operation_filter is on
```

The return has also changed, previous call , `get_account_history` and `get_relative_account_history` just return `operation_history_object`. This object does not have the date on it so the client need to query the node again with `block_num` to get a date. 

In this new call date is also returned in a pair among with `seconds_seq`. More on why this is needed will be described in the samples below.
 
In the most simple form the call will get the operations made by the account in a specified period of time:

```
alfredo@alfredo-Inspiron-5559 ~/CLionProjects/issue358_2 $ curl --data '{"jsonrpc": "2.0", "params": ["history", "get_account_history_by_date", ["1.2.282", "2015-12-18T00:00:00", "2015-12-19T00:00:00", 100, 0, false, 0]], "method": "call", "id": 10}' http://localhost:8090/rpc --silent  | jq
{
  "id": 10,
  "jsonrpc": "2.0",
  "result": [
    [
      [
        "2015-12-18T14:22:42",
        0
      ],
      {
        "id": "1.11.654752",
        "op": [
          5,
          {
            "fee": {
              "amount": 9529296,
              "asset_id": "1.3.0"
            },
            "registrar": "1.2.282",
            "referrer": "1.2.282",
            "referrer_percent": 0,
            "name": "bsip-0008",
            "owner": {
              "weight_threshold": 1,
              "account_auths": [],
              "key_auths": [
                [
                  "BTS7Q7CvT2a4d7vTRuM42yn2cg8GJcNV9rC3knakfdpKPB4G2DKwz",
                  1
                ]
              ],
              "address_auths": []
            },
            "active": {
              "weight_threshold": 1,
              "account_auths": [],
              "key_auths": [
                [
                  "BTS7K3BgQCUZhSF8nvNx94YveAijTUw3ofpc6v78bUWUPw8SMXwSr",
                  1
                ]
              ],
              "address_auths": []
            },
            "options": {
              "memo_key": "BTS7K3BgQCUZhSF8nvNx94YveAijTUw3ofpc6v78bUWUPw8SMXwSr",
              "voting_account": "1.2.0",
              "num_witness": 0,
              "num_committee": 0,
              "votes": [],
              "extensions": []
            },
            "extensions": {}
          }
        ],
        "result": [
          1,
          "1.2.99331"
        ],
        "block_num": 1888273,
        "trx_in_block": 0,
        "op_in_trx": 0,
        "virtual_op": 30892
      }
    ],
    [
      [
        "2015-12-18T14:23:21",
        0
      ],
      {
        "id": "1.11.654755",
        "op": [
          0,
          {
            "fee": {
              "amount": 3000000,
              "asset_id": "1.3.0"
            },
            "from": "1.2.282",
            "to": "1.2.99331",
            "amount": {
              "amount": 1000000000,
              "asset_id": "1.3.0"
            },
            "extensions": []
          }
        ],
        "result": [
          0,
          {}
        ],
        "block_num": 1888286,
        "trx_in_block": 0,
        "op_in_trx": 0,
        "virtual_op": 30895
      }
    ],
    [
      [
        "2015-12-18T14:29:45",
        0
      ],
      {
        "id": "1.11.654813",
        "op": [
          34,
          {
            "fee": {
              "amount": 200000,
              "asset_id": "1.3.0"
            },
            "owner": "1.2.282",
            "work_begin_date": "2015-12-19T00:00:00",
            "work_end_date": "2016-01-18T00:00:00",
            "daily_pay": 333333333,
            "name": "STEALTH",
            "url": "https://github.com/bitshares/bsips/blob/master/bsip-0008.md",
            "initializer": [
              1,
              {
                "pay_vesting_period_days": 1
              }
            ]
          }
        ],
        "result": [
          1,
          "1.14.18"
        ],
        "block_num": 1888414,
        "trx_in_block": 0,
        "op_in_trx": 0,
        "virtual_op": 30953
      }
    ],
    [
      [
        "2015-12-18T14:37:33",
        0
      ],
      {
        "id": "1.11.654949",
        "op": [
          6,
          {
            "fee": {
              "amount": 100006,
              "asset_id": "1.3.0"
            },
            "account": "1.2.282",
            "owner": {
              "weight_threshold": 1,
              "account_auths": [],
              "key_auths": [
                [
                  "BTS5WaszCsqVN9hDkXZPMyiUib3dyrEA4yd5kSMgu28Wz47B3wUqa",
                  1
                ]
              ],
              "address_auths": []
            },
            "active": {
              "weight_threshold": 1,
              "account_auths": [],
              "key_auths": [
                [
                  "BTS5TPTziKkLexhVKsQKtSpo4bAv5RnB8oXcG4sMHEwCcTf3r7dqE",
                  1
                ]
              ],
              "address_auths": []
            },
            "new_options": {
              "memo_key": "BTS5TPTziKkLexhVKsQKtSpo4bAv5RnB8oXcG4sMHEwCcTf3r7dqE",
              "voting_account": "1.2.5",
              "num_witness": 28,
              "num_committee": 8,
              "votes": [
                "1:22",
                "1:23",
                "1:24",
                "1:25",
                "1:26",
                "1:27",
                "1:28",
                "1:29",
                "1:30",
                "1:31",
                "1:32",
                "1:34",
                "1:36",
                "1:37",
                "1:38",
                "1:39",
                "1:40",
                "1:41",
                "1:44",
                "1:45",
                "1:46",
                "1:47",
                "1:49",
                "0:50",
                "1:51",
                "1:54",
                "1:56",
                "1:59",
                "1:60",
                "2:65",
                "2:66",
                "2:73",
                "0:76",
                "2:80",
                "0:84",
                "0:85",
                "0:87",
                "0:88",
                "0:90",
                "0:91",
                "2:92",
                "2:94",
                "2:95",
                "2:96",
                "2:100",
                "2:102",
                "2:104",
                "2:106",
                "2:108",
                "2:110",
                "2:115",
                "2:119"
              ],
              "extensions": []
            },
            "extensions": {}
          }
        ],
        "result": [
          0,
          {}
        ],
        "block_num": 1888570,
        "trx_in_block": 0,
        "op_in_trx": 0,
        "virtual_op": 31089
      }
    ],
    [
      [
        "2015-12-18T15:52:36",
        0
      ],
      {
        "id": "1.11.655851",
        "op": [
          0,
          {
            "fee": {
              "amount": 3000000,
              "asset_id": "1.3.0"
            },
            "from": "1.2.99331",
            "to": "1.2.282",
            "amount": {
              "amount": 997000000,
              "asset_id": "1.3.0"
            },
            "extensions": []
          }
        ],
        "result": [
          0,
          {}
        ],
        "block_num": 1890068,
        "trx_in_block": 0,
        "op_in_trx": 0,
        "virtual_op": 31991
      }
    ],
    [
      [
        "2015-12-18T16:21:09",
        0
      ],
      {
        "id": "1.11.656031",
        "op": [
          0,
          {
            "fee": {
              "amount": 3000000,
              "asset_id": "1.3.0"
            },
            "from": "1.2.20067",
            "to": "1.2.282",
            "amount": {
              "amount": 2672974818,
              "asset_id": "1.3.0"
            },
            "extensions": []
          }
        ],
        "result": [
          0,
          {}
        ],
        "block_num": 1890636,
        "trx_in_block": 0,
        "op_in_trx": 0,
        "virtual_op": 32171
      }
    ]
  ]
}
alfredo@alfredo-Inspiron-5559 ~/CLionProjects/issue358_2 $ 
```

This returns 6 operations. You can compare with the explorer for this account: http://bitshares-explorer.io/#/accounts/xeroc .
Currently at page 29 you can see 6 ops made 2017-12-18. Explorer uses `get_relative_account_history` so the comparassion make sense as they are using different calls but getting the same results.

We can now turn on the operation filter in the same interval and get just the transfers ops:

```
alfredo@alfredo-Inspiron-5559 ~/CLionProjects/issue358_2 $ curl --data '{"jsonrpc": "2.0", "params": ["history", "get_account_history_by_date", ["1.2.282", "2015-12-18T00:00:00", "2015-12-19T00:00:00", 100, 0, true, 0]], "method": "call", "id": 10}' http://localhost:8090/rpc --silent  | jq
{
  "id": 10,
  "jsonrpc": "2.0",
  "result": [
    [
      [
        "2015-12-18T14:23:21",
        0
      ],
      {
        "id": "1.11.654755",
        "op": [
          0,
          {
            "fee": {
              "amount": 3000000,
              "asset_id": "1.3.0"
            },
            "from": "1.2.282",
            "to": "1.2.99331",
            "amount": {
              "amount": 1000000000,
              "asset_id": "1.3.0"
            },
            "extensions": []
          }
        ],
        "result": [
          0,
          {}
        ],
        "block_num": 1888286,
        "trx_in_block": 0,
        "op_in_trx": 0,
        "virtual_op": 30895
      }
    ],
    [
      [
        "2015-12-18T15:52:36",
        0
      ],
      {
        "id": "1.11.655851",
        "op": [
          0,
          {
            "fee": {
              "amount": 3000000,
              "asset_id": "1.3.0"
            },
            "from": "1.2.99331",
            "to": "1.2.282",
            "amount": {
              "amount": 997000000,
              "asset_id": "1.3.0"
            },
            "extensions": []
          }
        ],
        "result": [
          0,
          {}
        ],
        "block_num": 1890068,
        "trx_in_block": 0,
        "op_in_trx": 0,
        "virtual_op": 31991
      }
    ],
    [
      [
        "2015-12-18T16:21:09",
        0
      ],
      {
        "id": "1.11.656031",
        "op": [
          0,
          {
            "fee": {
              "amount": 3000000,
              "asset_id": "1.3.0"
            },
            "from": "1.2.20067",
            "to": "1.2.282",
            "amount": {
              "amount": 2672974818,
              "asset_id": "1.3.0"
            },
            "extensions": []
          }
        ],
        "result": [
          0,
          {}
        ],
        "block_num": 1890636,
        "trx_in_block": 0,
        "op_in_trx": 0,
        "virtual_op": 32171
      }
    ]
  ]
}
alfredo@alfredo-Inspiron-5559 ~/CLionProjects/issue358_2 $ 
```

Asking for the limit orders created in that interval by xeroc gives an empty results as they were no op of that type:

```
alfredo@alfredo-Inspiron-5559 ~/CLionProjects/issue358_2 $ curl --data '{"jsonrpc": "2.0", "params": ["history", "get_account_history_by_date", ["1.2.282", "2015-12-18T00:00:00", "2015-12-19T00:00:00", 100, 0, true, 1]], "method": "call", "id": 10}' http://localhost:8090/rpc --silent  | jq
{
  "id": 10,
  "jsonrpc": "2.0",
  "result": []
}
alfredo@alfredo-Inspiron-5559 ~/CLionProjects/issue358_2 $ 
```

While the account_update op can be pulled as:

```
alfredo@alfredo-Inspiron-5559 ~/CLionProjects/issue358_2 $ curl --data '{"jsonrpc": "2.0", "params": ["history", "get_account_history_by_date", ["1.2.282", "2015-12-18T00:00:00", "2015-12-19T00:00:00", 100, 0, true, 6]], "method": "call", "id": 10}' http://localhost:8090/rpc --silent  | jq
{
  "id": 10,
  "jsonrpc": "2.0",
  "result": [
    [
      [
        "2015-12-18T14:37:33",
        0
      ],
      {
        "id": "1.11.654949",
        "op": [
          6,
          {
            "fee": {
              "amount": 100006,
              "asset_id": "1.3.0"
            },
            "account": "1.2.282",
            "owner": {
              "weight_threshold": 1,
              "account_auths": [],
              "key_auths": [
                [
                  "BTS5WaszCsqVN9hDkXZPMyiUib3dyrEA4yd5kSMgu28Wz47B3wUqa",
                  1
                ]
              ],
              "address_auths": []
            },
            "active": {
              "weight_threshold": 1,
              "account_auths": [],
              "key_auths": [
                [
                  "BTS5TPTziKkLexhVKsQKtSpo4bAv5RnB8oXcG4sMHEwCcTf3r7dqE",
                  1
                ]
              ],
              "address_auths": []
            },
            "new_options": {
              "memo_key": "BTS5TPTziKkLexhVKsQKtSpo4bAv5RnB8oXcG4sMHEwCcTf3r7dqE",
              "voting_account": "1.2.5",
              "num_witness": 28,
              "num_committee": 8,
              "votes": [
                "1:22",
                "1:23",
                "1:24",
                "1:25",
                "1:26",
                "1:27",
                "1:28",
                "1:29",
                "1:30",
                "1:31",
                "1:32",
                "1:34",
                "1:36",
                "1:37",
                "1:38",
                "1:39",
                "1:40",
                "1:41",
                "1:44",
                "1:45",
                "1:46",
                "1:47",
                "1:49",
                "0:50",
                "1:51",
                "1:54",
                "1:56",
                "1:59",
                "1:60",
                "2:65",
                "2:66",
                "2:73",
                "0:76",
                "2:80",
                "0:84",
                "0:85",
                "0:87",
                "0:88",
                "0:90",
                "0:91",
                "2:92",
                "2:94",
                "2:95",
                "2:96",
                "2:100",
                "2:102",
                "2:104",
                "2:106",
                "2:108",
                "2:110",
                "2:115",
                "2:119"
              ],
              "extensions": []
            },
            "extensions": {}
          }
        ],
        "result": [
          0,
          {}
        ],
        "block_num": 1888570,
        "trx_in_block": 0,
        "op_in_trx": 0,
        "virtual_op": 31089
      }
    ]
  ]
}
alfredo@alfredo-Inspiron-5559 ~/CLionProjects/issue358_2 $ 
```


note that with each operation, there is additional data added, this is time of the operation and seconds_sequence:

```
      [
        "2015-12-18T15:52:36",
        0
      ],
```

The `seconds_seq` is just a number that increments as the last op haves the same timestamp as the op before so if 2 operations are made by the account in the same block(independent of trx_in_block) the first will have a `seconds_seq` value of 0 and the second op a `seconds_seq` of 1. The number will continue incrementing until a new op came in with a different timestampt. This is done by the account_history plugin at replay.

I was able to find a use case of this in xeroc account and that is why i used it for all the samples.

At time `2015-10-30T09:34:18` more than 100 operations were done by this account:

```
alfredo@alfredo-Inspiron-5559 ~/CLionProjects/issue358_2 $ curl --data '{"jsonrpc": "2.0", "params": ["history", "get_account_history_by_date", ["1.2.282", "2015-10-30T09:34:18", "2015-11-01T00:00:00", 100, 0, false, 0]], "method": "call", "id": 10}' http://localhost:8090/rpc --silent  | jq
...
    [
      [
        "2015-10-30T09:34:18",
        99
      ],
      {
        "id": "1.11.141200",
        "op": [
          37,
          {
            "fee": {
              "amount": 0,
              "asset_id": "1.3.0"
            },
            "deposit_to_account": "1.2.282",
            "balance_to_claim": "1.15.97829",
            "balance_owner_key": "BTS4tX7bvbPBF4bKT3vH8WNUE3iiNsFawsjwPvpFhnk4y9VEtzqyi",
            "total_claimed": {
              "amount": 100000,
              "asset_id": "1.3.539"
            }
          }
        ],
        "result": [
          0,
          {}
        ],
        "block_num": 477885,
        "trx_in_block": 0,
        "op_in_trx": 99,
        "virtual_op": 41628
      }
    ]
  ]
}

```

Note the sequence in the last operation is at `99`. This means there are probably more ops in this block made by the same account.

Important: The client must check the sequence output and make an additional call if the number is at 99 as follows:

```
alfredo@alfredo-Inspiron-5559 ~/CLionProjects/issue358_2 $ curl --data '{"jsonrpc": "2.0", "params": ["history", "get_account_history_by_date", ["1.2.282", "2015-10-30T09:34:18", "2015-11-01T00:00:00", 100, 100, false, 0]], "method": "call", "id": 10}' http://localhost:8090/rpc --silent  | jq
{
  "id": 10,
  "jsonrpc": "2.0",
  "result": [
    [
      [
        "2015-10-30T09:34:18",
        100
      ],
      {
        "id": "1.11.141201",
        "op": [
          37,
          {
            "fee": {
              "amount": 0,
              "asset_id": "1.3.0"
            },
            "deposit_to_account": "1.2.282",
            "balance_to_claim": "1.15.46978",
            "balance_owner_key": "BTS5fN5vddLK3MoJnipRy8S8aYYfZhc4qiLLFeywtDV1Aef5fAwN2",
            "total_claimed": {
              "amount": 100000,
              "asset_id": "1.3.539"
            }
          }
        ],
        "result": [
          0,
          {}
        ],
        "block_num": 477885,
        "trx_in_block": 0,
        "op_in_trx": 100,
        "virtual_op": 41629
      }
    ],
    [
      [
        "2015-10-30T09:34:18",
        101
```

See how the call outputs ops that  start at sequence 100 in the above call.

That should be it with the samples.

I was not able to index `operation_type`, i mean, can index it but will not work filtering as if the index is already sorting by time it can't sort by op_type at the same time, at least i was not able to make it work.
Ended up just making the same as `get_account_history_operations` this is looping, comparing and excluding from result if there is no match.

I think a performance problem can be in a call like:

```
alfredo@alfredo-Inspiron-5559 ~/CLionProjects/issue358_2 $ curl --data '{"jsonrpc": "2.0", "params": ["history", "get_account_history_by_date", ["1.2.282", "2015-12-18T00:00:00", "2016-09-29T00:00:00", 100, 0, true, 44]], "method": "call", "id": 10}' http://localhost:8090/rpc --silent  | jq
{
  "id": 10,
  "jsonrpc": "2.0",
  "result": []
}
alfredo@alfredo-Inspiron-5559 ~/CLionProjects/issue358_2 $ 
```
Where the date range is big and no ops can be found. This actually returns empty results immediately so i am not sure how bad it can be.

Any help on dealing with this if you think it can be a problem will be appreciated.

**Comment by oxarbitrage** [comment]
understood, the size increase can be killer.

the problem is there is no way for a client app to get operation history inside a period of time without actually going throw almost all the requested account history. i think is needed.

how will you make it without adding size to the object ? i am open to any suggestion to make it happen.

forget the `seconds_seq` and `operation_type`, the time range is what actually matters.

**Comment by pmconrad** [comment]
Well, I don't have a solution ready to replace those fields.
What I mean is that they're redundant, i. e. account_transaction_history_object references an operation_history_object, and operation_history_object contains the operation (and its type) as well as the block_number (which uniquely maps to its block time).
I know that indexes can be function-based, so there should be a way to access these fields without actually storing them.

**Comment by oxarbitrage** [comment]
got it, thanks. ill give a try to functional index fields, could be a solution there.

**Comment by oxarbitrage** [comment]
will make new pull request for this as i had problems with the git.

**Pull request closed without merging**
