### PR TITLE
Add set_auto_subscription API

### PR DESCRIPTION
**Pull request by abitmore**
PR for #726. Also fixed some issues found in #777.

### CODE REVIEW

**Comment by abitmore** [comment]
When developing test cases I found some bugs related to #777. Also I found the test case for `enable_subscribe_to_all` is not working as expected. Will try to address them in this PR.

**Comment by sschiessl-bcp** [comment]
If auto subscription is off nothing gets subscribed except if full account has flag true, correct?

**Comment by abitmore** [comment]
@sschiessl-bcp yes.

**Comment by pmconrad** [comment]
Will this still be useful if https://github.com/bitshares/bitshares-fc/pull/126 gets merged and we extend API calls with an optional `subscribe` flag?

**Comment by abitmore** [comment]
IMHO it's still useful. Since we won't change default behavior, this approach would result in slightly smaller data traffic. Also I guess this approach is easier for existing clients to adapt (to modify their code). New clients can adopt this and/or the optional mechanism as they like.

**Comment by sschiessl-bcp** [comment]
> Will this still be useful if [bitshares/bitshares-fc#126](https://github.com/bitshares/bitshares-fc/pull/126) gets merged and we extend API calls with an optional `subscribe` flag?

Agreeing with @abitmore, will come in handy for UIs that are static still use WebSocket connection.

**Comment by abitmore** [comment]
Need to resolve conflicts due to #1765.

**Comment by abitmore** [comment]
Rebased to latest `develop` branch and force-pushed, conflicts resolved.

**Comment by abitmore** [comment]
Rebased to latest `develop` branch and force-pushed.

**Pull request merged**
