### PR TITLE
Add stacktrace on SIGSEGV

### PR DESCRIPTION
**Pull request by jmjatlanta**
This will enable a stacktrace dump when the SIGSEGV signal is raised.

The stacktrace will be written to the log if Boost is version 1.65 or greater, and the OS is Linux or Windows. Nothing will be written to the log if the Boost version is below 1.65.

To make the output human-legible, compile with at least some debug information (i.e. RelWithDebInfo or Debug)

### CODE REVIEW

**Comment by pmconrad** [comment]
Also in `cli_wallet`?

**Comment by jmjatlanta** [comment]
> Also in `cli_wallet`?

Good question. I hesitated, as I assumed a crash there is a bit easier to figure out, and I didn't want the real problem scrolling off the screen. It is a one-liner to add it. If you think it should be there, I'll be happy to include it. Just say the word.

**Comment by pmconrad** [comment]
Hm. Please?

I think the real cause of a SIGSEGV will rarely show itself. Stacktrace will usually be more helpful than whatever scrolls off-screen.

**Comment by pmconrad** [comment]
I think this works better than expected.

**Comment by abitmore** [comment]
There is a typo in commit history (SIGSEV->SIGSEGV), @jmjatlanta I guess it's easy to fix?

**Comment by pmconrad** [comment]
@abitmore please re-review.

**Pull request merged**
