### PR TITLE
Generate uia sharedrop genesis

### PR DESCRIPTION
**Pull request by xeroc**
Tried to move over the generate_genesis plugin as written by blocktrades for peerplays:
https://github.com/PBSA/peerplays/tree/master/libraries/plugins/

Needs testing

### CODE REVIEW

**Comment by pmconrad** [comment]
Question: do we want to modify db_init? This is no longer the generic graphene repo, this is bitshares-core. We won't be using a new genesis.

**Comment by xeroc** [comment]
> Question: do we want to modify db_init? This is no longer the generic graphene repo, this is bitshares-core. We won't be using a new genesis.

Yhea. This bothers me too. But if you really want to build a new genesis, you also need the code that loads the data from the genesis block. No?
I personally, don't need this in db_init .. maybe we should remove it there and just keep the new structs

**Comment by xeroc** [comment]
Just removed the modifications to `db_init.cpp`

**Comment by pmconrad** [comment]
It seems you have rolled back too far... flat_index is back... :-(

If possible keep the changes local to the plugin directory. Don't modify the genesis header file.

**Comment by xeroc** [comment]
Dang .. I made a checkout of that file from master and havent updated local branch. Sorry for that .. will fix

**Comment by abitmore** [comment]
IMHO no need to merge this into develop branch, instead, we can create a new branch for it and merge develop/master to the new branch when needed.

**Comment by pmconrad** [comment]
Needs a rebase and a unit test suite. I don't see this in the upcoming feature release.

**Comment by pmconrad** [comment]
IMO this serves no real purpose.

Anyone who is going to sharedrop will most likely have their own idea how that sharedrop is going to happen, so a specific implementation is of little use. A better option for sharedropping might be to use the snapshot plugin and some scripting to generate a genesis from the snapshot.

To avoid the bloat I'd prefer to close this. Opinions?

**Pull request closed without merging**
