### PR TITLE
Auto login on every ws/rpc connection using HTTP Authorization header if present

### PR DESCRIPTION
**Pull request by elmato**
This PR will allow to: 

**Use the name of the APIs when calling.**

`curl --data '{"jsonrpc": "2.0", "params": ["history", "get_account_history", ["1.2.31489", "1.11.0", 10, "1.11.0"]], "method": "call", "id": 10}' http://testgraphene:8090/rpc`

**Specify the credentials using standard HTTP Headers** (if the API is restricted)

`curl -u bytemaster:supersecret --data '{"jsonrpc": "2.0", "params": ["history", "get_account_history", ["1.2.31489", "1.11.0", 10, "1.11.0"]], "method": "call", "id": 10}' http://testgraphene:8090/rpc`

**Prevent unnecessary round trips (login, query API number, call function) when using WS**
`wscat -c ws://bytemaster:supersecret@testgraphene:8090`  

Needs the following FC library PRs to work

**Add access to HTTP request headers in websocket_connection**
https://github.com/bitshares/bitshares-fc/pull/1

**Replace the call to get_api_by_name**
https://github.com/bitshares/bitshares-fc/pull/2

It also preserve:
 * Same default api access permissions 
 * Possibility to use numbers to specify the API
 * Default API numbers (database = 0, login = 1)
 * Old ws mechanics => connect / login / query api number / call

### CODE REVIEW

**Comment by xeroc** [comment]
I want this!

**Comment by oxarbitrage** [comment]
@elmato this looks very good, i am downloading and test it to make a review.

**Comment by oxarbitrage** [comment]
compiling the pull request i am getting the following compilation error:

`[ 78%] Built target graphene_account_history
[ 79%] Building CXX object libraries/app/CMakeFiles/graphene_app.dir/application.cpp.o
/home/alfredo/bitshares-2/libraries/app/application.cpp: In member function ‘void graphene::app::detail::application_impl::new_connection(const websocket_connection_ptr&)’:
/home/alfredo/bitshares-2/libraries/app/application.cpp:251:32: error: ‘class fc::http::websocket_connection’ has no member named ‘get_request_header’
          std::string auth = c->get_request_header("Authorization");
                                ^
In file included from /home/alfredo/opt/boost_1_57_0/include/boost/filesystem/path_traits.hpp:23:0,
                 from /home/alfredo/opt/boost_1_57_0/include/boost/filesystem/path.hpp:25,
                 from /home/alfredo/bitshares-2/libraries/app/application.cpp:51:
/home/alfredo/opt/boost_1_57_0/include/boost/system/error_code.hpp: At global scope:
/home/alfredo/opt/boost_1_57_0/include/boost/system/error_code.hpp:221:36: warning: ‘boost::system::posix_category’ defined but not used [-Wunused-variable]
     static const error_category &  posix_category = generic_category();
                                    ^
/home/alfredo/opt/boost_1_57_0/include/boost/system/error_code.hpp:222:36: warning: ‘boost::system::errno_ecat’ defined but not used [-Wunused-variable]
     static const error_category &  errno_ecat     = generic_category();
                                    ^
/home/alfredo/opt/boost_1_57_0/include/boost/system/error_code.hpp:223:36: warning: ‘boost::system::native_ecat’ defined but not used [-Wunused-variable]
     static const error_category &  native_ecat    = system_category();
                                    ^
make[2]: *** [libraries/app/CMakeFiles/graphene_app.dir/application.cpp.o] Error 1
make[1]: *** [libraries/app/CMakeFiles/graphene_app.dir/all] Error 2
make: *** [all] Error 2
alfredo@graphene:~/bitshares-2$
`

are we sure all fil modifications are included ?

**Comment by elmato** [comment]
@oxarbitrage, You need to incorporate the followings PRs in the FC library.

**Add access to HTTP request headers in websocket_connection**
https://github.com/bitshares/bitshares-fc/pull/1

**Replace the call to get_api_by_name**
https://github.com/bitshares/bitshares-fc/pull/2

**Comment by oxarbitrage** [comment]
got it, thanks @elmato . everything worked perfect, great job.

some testing output:

1- no credentials, blocked history api access for the no login user:

`alfredo@graphene:~/bitshares-2/libraries/app$ curl --data '{"jsonrpc": "2.0", "params": ["history", "get_account_history", ["1.2.17", "1.11.0", 10, "1.11.0"]], "method": "call", "id": 10}' http://localhost:8090/rpc
{"id":10,"error":{"code":1,"message":"10 assert_exception: Assert Exception\n_history_api: \n    {}\n    th_a  api.cpp:210 history\n\n    {\"call.method\":\"call\",\"call.params\":[\"history\",\"get_account_history\",[\"1.2.17\",\"1.11.0\",10,\"1.11.0\"]]}\n    th_a  websocket_api.cpp:110 on_message","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"api.cpp","line":210,"method":"history","hostname":"","thread_name":"th_a","timestamp":"2017-01-31T00:06:57"},"format":"_history_api: ","data":{}},{"context":{"level":"warn","file":"websocket_api.cpp","line":110,"method":"on_message","hostname":"","thread_name":"th_a","timestamp":"2017-01-31T00:06:57"},"format":"","data":{"call.method":"call","call.params":["history"alfredo@graphene:~/bitshares-2/libraries/app$
`

2- wrong username or password, exception:

`alfredo@graphene:~/bitshares-2/libraries/app$ curl -u bytemaster:aja --data '{"jsonrpc": "2.0", "params": ["history", "get_account_history", ["1.2.17", "1.11.0", 10, "1.11.0"]], "method": "call", "id": 10}' http://localhost:8090/rpc
{"id":10,"error":{"code":1,"message":"10 assert_exception: Assert Exception\n_history_api: \n    {}\n    th_a  api.cpp:210 history\n\n    {\"call.method\":\"call\",\"call.params\":[\"history\",\"get_account_history\",[\"1.2.17\",\"1.11.0\",10,\"1.11.0\"]]}\n    th_a  websocket_api.cpp:110 on_message","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"api.cpp","line":210,"method":"history","hostname":"","thread_name":"th_a","timestamp":"2017-01-31T00:07:53"},"format":"_history_api: ","data":{}},{"context":{"level":"warn","file":"websocket_api.cpp","line":110,"method":"on_message","hostname":"","thread_name":"th_a","timestamp":"2017-01-31T00:07:53"},"format":"","data":{"call.method":"call","call.params":["history"alfredo@graphene:~/bitshares-2/libraries/app$
`

3- correct data worked:

`alfredo@graphene:~/bitshares-2/libraries/app$ curl -u bytemaster:supersecret --data '{"jsonrpc": "2.0", "params": ["history", "get_account_history", ["1.2.17", "1.11.0", 10, "1.11.0"]], "method": "call", "id": 10}' http://localhost:8090/rpc
{"id":10,"result":[{"id":"1.11.3","op":[5,{"fee":{"amount":514746,"asset_id":"1.3.0"},"registrar":"1.2.17","referrer":"1.2.17","referrer_percent":0,"name":"my-account55","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["BTS6rJg81HQ7TkhteXi7BXfrnoCNxeTYbd3kvy1xgJc8fMk3bUWk9",1]],"address_auths":[]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["BTS8gBgE6fbJg2CpNZqwXy4vwSXz3StwyFEH4a3fWKRdErZ9sBPEK",1]],"address_auths":[]},"options":{"memo_key":"BTS7BjffeEcEVbhUZ2ASN6k1GwxRbsEbwPjhJDBCxjiKivTBhwNGA","voting_account":"1.2.5","num_witness":0,"num_committee":0,"votes":[],"extensions":[]},"extensions":{}}],"result":[1,"1.2.19"],"block_num":42,"trx_in_block":0,"op_in_trx":0,"virtual_op":11},{"id":"1.11.2","op":[5,{"fee":{"amount":514746,"asset_id":"1.3.0"},"registrar":"1.2.17","referrer":"1.2.17","referrer_percent":0,"name":"my-account33","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["BTS6rJg81HQ7TkhteXi7BXfrnoCNxeTYbd3kvy1xgJc8fMk3bUWk9",1]],"address_auths":[]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["BTS53YFiNmaohgEoeEtwQ3jJkG4AKwUKDvqPBMthEFrmZPKgNfoaM",1]],"address_auths":[]},"options":{"memo_key":"BTS7UYr2E8TjR82VvXBhCPE1yzF9LtfPf6YWtfYXbKezJDoUnGibH","voting_account":"1.2.5","num_witness":0,"num_committee":0,"votes":[],"extensions":[]},"extensions":{}}],"result":[1,"1.2.18"],"block_num":41,"trx_in_block":0,"op_in_trx":0,"virtual_op":8},{"id":"1.11.1","op":[8,{"fee":{"amount":1000000000,"asset_id":"1.3.0"},"account_to_upgrade":"1.2.17","upgrade_to_lifetime_member":true,"extensions":[]}],"result":[0,{}],"block_num":40,"trx_in_block":1,"op_in_trx":0,"virtual_op":5}]}alfredo@graphene:~/bitshares-2/libraries/app$

`

4- calling function from another api with wrong credentials, exception:

`alfredo@graphene:~/bitshares-2/libraries/app$ curl -u bytemaster:testing --data '{"jsonrpc": "2.0", "params": ["network_node", "get_info", []], "method": "call", "id": 10}' http://localhost:8090/rpc
{"id":10,"error":{"code":1,"message":"10 assert_exception: Assert Exception\n_network_node_api: \n    {}\n    th_a  api.cpp:198 network_node\n\n    {\"call.method\":\"call\",\"call.params\":[\"network_node\",\"get_info\",[]]}\n    th_a  websocket_api.cpp:110 on_message","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"api.cpp","line":198,"method":"network_node","hostname":"","thread_name":"th_a","timestamp":"2017-01-31T00:18:11"},"format":"_network_node_api: ","data":{}},{"context":{"level":"warn","file":"websocket_api.cpp","line":110,"method":"on_message","hostname":"","thread_name":"th_a","timestamp":"2017-01-31T00:18:11"},"format":"","data":{"call.method":"call","call.params":["network_node","get_info",[]]}}]}}}alfredo@graphene:~/bitshares-2/libraries/app$
`
5- calling the same with correct data:

`alfredo@graphene:~/bitshares-2/libraries/app$ curl -u bytemaster:supersecret --data '{"jsonrpc": "2.0", "params": ["network_node", "get_info", []], "method": "call", "id": 10}' http://localhost:8090/rpc
{"id":10,"result":{"listening_on":"0.0.0.0:36806","node_public_key":"03aece4c00e02dfdc6bf0b803ea32c3ccae2c6e505bdab918781ef7705b0f3c189","node_id":"88917f4d62d828397c8852fdc194fa6f84b1d911be78d299f12594c17fb5327447","firewalled":"unknown","connection_count":0}}alfredo@graphene:~/bitshares-2/libraries/app$
`

**Pull request merged**
