### PR TITLE
Develop to release 3.1.0

### PR DESCRIPTION
**Pull request by abitmore**

### CODE REVIEW

**Comment by abitmore** [comment]
In https://github.com/bitshares/bitshares-core/pull/1744 we merged `develop` (HEAD was c737ea5)  to `testnet`, skipped `release`. This PR is to redo the skipped step.

**Comment by jmjatlanta** [comment]
In comparing #1758 to this one, here are the differences:

- This one does not bump GRAPHENE_CURRENT_DB_VERSION. This should normally not be needed, but due to a procedural oversight, must be done in this release
- This one wants to merge into a branch called "release" whereas #1758 wants to merge to "master"
   - This PR will require an extra step, but the naming of the branch in #1758 is not intuitive.

**Comment by abitmore** [comment]
I'll renew the `release` branch. Closing this one.

**Comment by abitmore** [comment]
I'll renew the `release` branch. Closing this one.

**Pull request closed without merging**
