### PR TITLE
Fix for Windows build (cli_test and socket.h)

### PR DESCRIPTION
**Pull request by jmjatlanta**
This is a potential fix for Issue #1292 

It is untested, as I do not have a working Windows build environment. I formalized this into a PR to make it easier to test.

Note: This PR is (currently) based on the ``develop`` branch.

### CODE REVIEW

**Comment by ryanRfox** [comment]
@abitmore are you willing to test this one? We may want to add the `0 Help Wanted` label to attract other Windows build testers.

**Comment by abitmore** [comment]
I feel it's better to reuse related code in FC but not reinvent wheels here.

**Comment by jmjatlanta** [comment]
@abitmore says:
> can we just return it after the bind to avoid calling bind twice?

We have the Application class, and in the real world we pass in boost::program_options for what port to bind to for P2P communication as well as API connections. If we do not specify these parameters, I believe they do not bind to ports. Are you saying we should pass parameters to the Application class to tell it to select its own unused port, and then we can later query for which ports it binds to? I know that you know that such a change is out of the scope of this fix, so I must be misunderstanding your question.

**Comment by jmjatlanta** [comment]
> if no port is passed in, it will either not bind, or bind to a random available port

Let me see if I am clear: 

For P2P, if we don't specify a port,  it binds to a random available port. Querying afterward makes sense, and is already implemented.

For the rpc endpoint, the user has the option to pass in a port number. In the "real world" they will either (1) not want one, or (2) have one in mind so that they can connect their clients to it. In the "testing world" we just want a random port, and don't need to share that port number with anyone outside the test.

I believe what you are proposing is for tests to set the parameter "rpc-endpoint" to something like "127.0.0.1:0" and let the websocket server select an available port. We can then provide an ``application`` member method to query the websocket server to reveal the port selected.

**Comment by abitmore** [comment]
Thanks for the explanation. I guess I was wrong (was thinking about p2p port while the function is about rpc port). To be clear, in the real world, I don't want the feature to bind to a random rpc port, so it doesn't make sense to have it just for test (even if we have it, we still need to test specified port).

**Comment by abitmore** [comment]
```
   close(socket_fd);
```
```
tests\cli\main.cpp(105): error C3861: 'close': identifier not found
```

**Comment by abitmore** [comment]
```
boost/test/unit_test_suite_impl.hpp(343): error C2248: 'MyInitialization::~MyInitialization': cannot access private member declared in class 'MyInitialization'
```

**Comment by abitmore** [comment]
> error C2248: 'MyInitialization::~MyInitialization': cannot access private member declared in class 'MyInitialization'

Update: moving the WSA initialization/cleanup code to `cli_fixture` struct fixes the issue.

In additional, `/bigobj` is required for `cli_tests`

**Pull request merged**
