### PR TITLE
Add api-access console log to node startup when present

### PR DESCRIPTION
**Pull request by oxarbitrage**
requested at https://github.com/bitshares/bitshares-core/issues/331

### CODE REVIEW

**Comment by pmconrad** [comment]
IMO the real problem in #331 is the lack of a proper error message if the file cannot be found.

**Comment by oxarbitrage** [comment]
agree, added commit to consider file existence.

some output when file specified in the config.ini but does not exist in the filesystem:

```
91381ms th_a       object_database.cpp:94        open                 ] Opening object database from /home/alfredo/CLionProjects/pull332/data/my-blockprod/blockchain ...
98777ms th_a       object_database.cpp:100       open                 ] Done opening object database.
98777ms th_a       application.cpp:471           startup              ] Failed to load file from /path/to/nowhere.json
alfredo@alfredo-Inspiron-5559 ~/CLionProjects/pull332 $ 
```

file exists:

```
300097ms th_a       application.cpp:466           startup              ] Using api access file from /home/alfredo/CLionProjects/pull332/data/my-blockprod/apiaccess.json
```

let me know what do you think.

**Comment by xeroc** [comment]
Desperately needed patch! Thanks

**Comment by pmconrad** [comment]
Looks good to me. ACK.

**Pull request merged**
