### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lososeg**
I did not have enough make, automake and libtool packages to build on ubuntu 16.04.

### CODE REVIEW

**Comment by abitmore** [comment]
Thanks.

We can merge it to `master` branch now because `master` is the default branch, most people will read docs in `master` branch.

We need to cherry-pick it to `develop` branch as well.

**Comment by oxarbitrage** [comment]
are we sure we need `automake` ? 

`make` is needed and `libtool` just as 14.04: https://github.com/bitshares/bitshares-core/wiki/BUILD_UBUNTU#ubuntu-1404-lts-64-bit-build-and-install-instructions

is this needed? https://github.com/bitshares/bitshares-core/wiki/BUILD_UBUNTU#ubuntu-1604-lts-64-bit

**Comment by lososeg** [comment]
I had a error “failed to run aclocal: No such file or directory”. And it was decided only after installing automake (make was already installed)

**Comment by abitmore** [comment]
@lososeg I guess you're using an Ubuntu "minimal" installation or similar. Ubuntu 16.04 server installation by default will have the 3 packages you mentioned.

**Comment by lososeg** [comment]
May be, I test it on hetzner's VDS.

**Pull request merged**
