### PR TITLE
Fix #783, add limitations to more APIs

### LINKED ISSUE #783: Review limitations on API's
Some API's have a `limit` parameter but don't check whether it's too big. Inspired by https://github.com/bitshares/bitshares-core/issues/781#issuecomment-375940158.

Be careful since changes may break client applications.

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [x] Refine User Stories / Requirements
- [x] Define Test Cases
- [ ] Design / Develop Solution
  - [x] Assigned: @manikey123
      - [ ] `get_limit_orders`
      - [ ] `get_call_orders`
      - [ ] `get_settle_orders`
      - [ ] `get_order_book`
  - [x] Estimated:
      - [x] 3 hours per API (12 hours total for research, implementation, testing and documentation)
  - [ ] Remittance: Pending
- [ ] Perform QA/Testing
- [ ] Update Documentation

### PR DESCRIPTION
**Pull request by manikey123**
this is the fix for 783 and 782 updates for merge changes and  plugin changes

### CODE REVIEW

**Comment by abitmore** [comment]
It's not clear enough to only put issue number in title, please update.

BTW there are lots of commits with same comment "updated indents", why not combine/squash them? Also still some indents aren't fixed.

**Comment by abitmore** [comment]
Is this a replacement of #1513? At a glance there are same changes in both pull requests.

**Comment by pmconrad** [comment]
Hm, I think if we merge #1513 this PR should reduce itself to the new stuff more or less automatically.

@manikey123 please fix the conflict in #1513 first so we can merge that, then we'll continue here.

**Comment by manikey123** [comment]
@abitmore I have squashed and rebased the indent updates commits for the PR.
#783 fixes need the #782 changes. I would need to redo that again for #783 as the changes do not exist in the develop branch. 
Can everything be fixed in this PR?
Do suggest @pmconrad @abitmore

**Comment by abitmore** [comment]
@manikey123 I think it's better to resolve the conflicts in #1513 as Peter suggested so we can merge that one first. Because Peter has took efforts to review that PR, continuing working there would make his life easier. After #1513 is merged, we can rebase this one.

By the way, please learn to write informative commit comments, see https://chris.beams.io/posts/git-commit/. Squashing all commits into one is not the best. Also there are guidelines mentioned in https://github.com/bitshares/bitshares-core/issues/1318.

**Comment by manikey123** [comment]
making a new pr to have new develop branch code with 782 fixes in it

**Pull request closed without merging**
