### PR TITLE
Add Matrix Build Support to Travis-CI Integration

### PR DESCRIPTION
**Pull request by marcialvieira**
Fix for #1233

### CODE REVIEW

**Comment by oxarbitrage** [comment]
Hey @marcialvieira thank you for submitting this. 

I am unsure if we can use it with our current limitation of 50 minutes max in travis. We are in the process of merging https://github.com/bitshares/bitshares-core/pull/1417 that will speed up a bit but probably not enough to make the build for 2 Operation Systems as this pull attempt to do.

Still, i am considering and discussing with the team a possible upgrade in travis to a paid plan that will allow unlimited build time.

**Comment by marcialvieira** [comment]
Hi, thanks for replying, maybe some modifications can also be made to reduce compilation time, increasing the number of jobs (I mean -j), but this will increase memory usage and may abort because of that, change from Debug to Release, so debug symbols don't be added, add some parameters like -pipe or switch compiler, to clang for example.

**Comment by pmconrad** [comment]
Please rebase on latest develop.
The osx build has failed, please check.

**Comment by marcialvieira** [comment]
Working on it.

**Comment by marcialvieira** [comment]
Job aborted for time limit during the test, but reading the logs I'm convinced that everything is fine [marcialvieira/bitshares-core](https://travis-ci.com/marcialvieira/bitshares-core/builds/102826654)

**Comment by pmconrad** [comment]
> `Test setup error: boost::runtime::access_to_missing_argument: There is no argument provided for parameter color_output`

This does not look good. Possible cause: https://stackoverflow.com/questions/39171467/there-is-no-argument-provided-for-parameter-color-output-with-boost-test-and-cte

Can you reproduce this locally? @jmjatlanta did you ever see that?

Maybe need to add code like this to `tests/CMakeLists.txt`: https://github.com/bitshares/bitshares-fc/blob/master/CMakeLists.txt#L411-L417

**Comment by jmjatlanta** [comment]
I have not seen that before. I will attempt to recreate it on my mac.

**Comment by pmconrad** [comment]
Perhaps it depends on boost version?

**Comment by marcialvieira** [comment]
Yeah, looking into it.

**Comment by marcialvieira** [comment]
Giving a try without installing boost@1.60, using the default travis-ci image (boost 1.67.0_1) since @jmjatlanta told me that he successfully built using 1.68 on his mac.

**Review by mdds995 — APPROVED** [review]

**Comment by abitmore** [comment]
Obsolete by https://github.com/bitshares/bitshares-core/pull/2062 and following changes. Our main CI process is now on Github Actions.

**Pull request closed without merging**
