### PR TITLE
Bump docs submodule

### PR DESCRIPTION
**Pull request by abitmore**
Discussion:
* do we need to keep the docs submodule and bump it now and then? Currently it links to wiki.
* merge docs PR to `master` branch or another?

Updated git-flow.

### CODE REVIEW

**Comment by oxarbitrage** [comment]
i think we should do this in `develop` closer to release date and leave the merge into `master` to update the docs submodule to the last wiki versions.

note: by now i submit updates to wiki from time to time(when i find a bug or want to add something) but nobody actually see it. for example i updated https://github.com/bitshares/bitshares-core/wiki/ElasticSearch-Plugin and https://github.com/bitshares/bitshares-core/wiki/private-testnet in the last few days.
i think this flow will be better when we have a repo where we can send pull requests or commits to the doc.

**Comment by cogutvalera** [comment]
IMHO everything must have history of what we are doing: coding, documentation, etc ...
So we have to make repo instead of using wiki. This submodule/repo and any other sumbodule/repo is something like complete project. I wish to see everywhere repo for coding and for documentation too and for any other aspects, in order to have all advantages from git.

**Comment by abitmore** [comment]
@cogutvalera Github Wiki does use git thus has commit history.

**Comment by cogutvalera** [comment]
Maybe better idea will be to have decentralized git or something similar very much that would be tied completely and fully with Blockchain technology, maybe some kind of plugin for BitShares, but it would be a great job maybe in future and not now, a lot of discussion required before starting development of decentralized git. Just as an example https://medium.com/@alexberegszaszi/mango-git-completely-decentralised-7aef8bcbcfe6 , just for the info maybe useful I hope :-) If this direction is really required for BitShares project (code, documentation, etc) let's create something like new issue maybe and after that maybe as a new BSIP. I think it would be really cool if all code, documentation, etc would be kept safely in BitShares Blockchain itself, isn't it really cool ? So we won't lose very important data never ! Just my thoughts/opinion ...

**Comment by cogutvalera** [comment]
@abitmore I don't mean only history, I mean all advantages like @oxarbitrage said PRs, etc ...

**Pull request merged**
