### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by omahs**
Fix typos

### CODE REVIEW

**Comment by abitmore** [comment]
Hi @omahs, thanks for the pull request.

I noticed that you create a lot of "fix typos" pull requests in a lot of different repositories, do you use a bot to scan the repositories for spelling issues? To be honest, this looks suspicious. By default, pull requests from first-time contributors require approval from a maintainer to start CI tests. One potential risk is that if someone submits a small pull request before submitting a second with malicious code, this would automatically run all configured workflows because that person is no longer a first-time contributor. I'm not saying you will do this, but for security reasons I won't merge this pull request. Hope you can understand. Thank you anyway.

**Comment by omahs** [comment]
Hey @abitmore, Thanks for your message. I don't use bots but generally check documentation files (.md, .rst, .mdx…) for spelling mistakes.
I'm just a regular human (not a dev or engineer) who tries to contribute to documentation in many blockchain repositories, hoping I can have a positive impact.
I understand your security issue, no worries.

**Comment by abitmore** [comment]
> Hey @abitmore, Thanks for your message. I don't use bots but generally check documentation files (.md, .rst, .mdx…) for spelling mistakes. I'm just a regular human (not a dev or engineer) who tries to contribute to documentation in many blockchain repositories, hoping I can have a positive impact. I understand your security issue, no worries.

Thanks for the clarification. Just out of curiousity, if you're not using bots, I guess you must be using some efficient tools, right? According to your Github profile, during this month, you created 208 commits in 104 repositories and opened another 181 pull requests in 170 repositories, which I don't think a human who "generally checks documentation files" can achieve manually. And the tools must be very smart, as in https://github.com/oceanbase/oceanbase/pull/1577 it can even fix typos in comments and log messages in the source code (.h and .cpp files).

image

image

**Comment by omahs** [comment]
@abitmore I legit use only basic tools, like the github search feature and grammarly. I actually wish I was able to code something efficient for a better workflow. If I had such a bot I would then be able to find way more misspellings. I do dedicate a lot of time to this though and I know it's unusual.

**Comment by abitmore** [comment]
Hi @omahs, that might have taken you a lot of time. Thank you anyway.
I will include your changes and credit you in the next pull request that updates the README (which is #2786). Thank you again.

> @abitmore I legit use only basic tools, like the github search feature and grammarly. I actually wish I was able to code something efficient for a better workflow. If I had such a bot I would then be able to find way more misspellings. I do dedicate a lot of time to this though and I know it's unusual.

**Pull request closed without merging**
