### PR TITLE
Segregate obnoxiously slow test

### PR DESCRIPTION
**Pull request by abitmore**
Cherry-picked from #1126. 

@nathanhourt wrote:
>The main test driver should run fairly quickly; extremely slow tests should be moved to a
separate driver so developer time isn't wasted waiting for many runs of a slow test.
>
>Really more tests should be moved over, but I'm too lazy right now.

I wrote:
> There were efforts to include all consensus related tests into `chain_test`. Moving tests outside of `chain_test` will likely make them be ignored and may cause unexpected consequences.

More input wanted. Thanks.

### CODE REVIEW

**Comment by jmjatlanta** [comment]
My opinion: All tests should run by default. Perhaps we can subdivide tests yet again? ``./chain-test --run_test=fast_tests/*``

**Comment by abitmore** [comment]
Thanks to @pmconrad, Travis build is now much faster, I think we can add more tests there.

**Comment by pmconrad** [comment]
Agree with @jmjatlanta - all tests should be run by default. call_order_tests takes 10 seconds on my desktop, that's nothing.
IMO can close this PR without merging.

**Comment by pmconrad** [comment]
No further comments - closing.

**Pull request closed without merging**
