### PR TITLE
Too restrictive check in market fee sharing

### PR DESCRIPTION
**Pull request by OpenLedgerApp**
Issue: #1774
Created new hardfork
Added unit tests

### CODE REVIEW

**Comment by OpenLedgerApp** [comment]
Issue: https://github.com/bitshares/bitshares-core/issues/1774

**Comment by abitmore** [comment]
@OpenLedgerApp too many commits. Please **rebase** to latest `hardfork` and force-push.

**Comment by abitmore** [comment]
It's not necessary to close this if rebased correctly.

**Comment by abitmore** [comment]
I mean use the `git rebase origin/hardfork` command.

**Comment by OpenLedgerApp** [comment]
Can't reopen this PR after rebase to latest hardfork and force-push. Create a new one (#1848)

**Comment by abitmore** [comment]
I guess you deleted the branch from github so this PR got closed automatically, in this case it could be unable to reopen.

**Comment by OpenLedgerApp** [comment]
No. I closed it manually (it was a mistake), then fixed issue-1774 branch, then force-pushed changes. After that "Reopen and commit" button not work, reason: branch changed and force-pushed.

**Comment by abitmore** [comment]
Oh. Should reopen first then force-push.

**Pull request closed without merging**
