### PR TITLE
[#383] Fix a crash in which we tried to log a proposal object that may have been deleted.

### LINKED ISSUE #383: An exception that is thrown logs an object that has been deleted
Credits to @dnotestein and team.

In [this line](https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_block.cpp#L295), we throw an exception with `(proposal)` but we might have deleted `proposal` in [a previous line](https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_block.cpp#L274).

### PR DESCRIPTION
**Pull request by abitmore**
Fix #383.

### CODE REVIEW

**Comment by abitmore** [comment]
Need to fix the referencing to `proposal_object` in [clean_expired_proposals](https://github.com/bitshares/bitshares-core/blob/develop/libraries/chain/db_update.cpp#L185-L187) as well.
```
      } catch( const fc::exception& e ) {
         elog("Failed to apply proposed transaction on its expiration. Deleting it.\n${proposal}\n${error}",
              ("proposal", proposal)("error", e.to_detail_string()));
      }
      remove(proposal);
```

**Comment by abitmore** [comment]
Actually, what does it mean if `session.merge()` throws an exception? I think it's better to let the program crash in this case. @pmconrad what do you think?

**Comment by pmconrad** [comment]
session.merge() throwing should be considered serious, yes. Most likely cause would probably be an out-of-memory or similarly fatal error.
Problem is, FC_*_RETHROW always throw fc::exception, so after this we cannot easily distinguish our own application exceptions from system exceptions anymore. Due to this, I think out-of-memory isn't really handled properly throughout the whole codebase. Which means it doesn't make much sense to clean it up here and now.

**Comment by pmconrad** [comment]
Like I commented in #383 the crash should never occur in practice, because what happens after the remove() should never throw an exception. OTOH capturing the proposal that caused the exception provides helpful information.
Therefore I think the fix in its current form does much harm and little good.
IMO close this PR and close #383 as WONTFIX.

**Pull request closed without merging**
