### PR TITLE
Add genesis-dev.json

### PR DESCRIPTION
**Pull request by nathanhourt**
With the --create-genesis-json flag going away, we should keep a
copy of the file it created, as this file is the easiest way to get
a local development testnet up and creating blocks. Also add a copy
of the corresponding private key in genesis-dev-key.txt

### CODE REVIEW

**Comment by pmconrad** [comment]
IMO we shouldn't clutter the project root with this. I still think this belongs in the docs.

Btw, I've never seen the need to set up a local testnet.

**Comment by cogutvalera** [comment]
> IMO we shouldn't clutter the project root with this. I still think this belongs in the docs.
> 
> Btw, I've never seen the need to set up a local testnet.

I need to set up a local testnet for Hack The DEX for example

**Comment by nathanhourt** [comment]
> IMO we shouldn't clutter the project root with this. I still think this belongs in the docs.
>
> Btw, I've never seen the need to set up a local testnet.

Sure ya have... Have you ever run the tests? Those all run on local testnets; the test framework just uses the `genesis_state_type` struct directly rather than writing it out to a JSON file, which is all this commit is: a default-constructed `genesis_state_type` written to JSON.

###### Technically, though, I wrote the test framework, so maybe I'm just agreeing with myself...

Nevertheless, I concede: adding two new files to the root of the source tree for this is excessive. However, I would like to keep it a bit closer at hand than squirreled away in the docs. I've helped two different people with their local BTS dev nets within the last week. It's definitely something people do, and I want to make it easy for them.

What if we just throw these files in `programs/genesis_util` instead? Is that a better place for them?

**Comment by pmconrad** [comment]
Either there or in `libraries/egenesis`. While you're at it, maybe move the master `genesis.json` also down there?

**Comment by nathanhourt** [comment]
Ooh, even better. OK, done.

I moved genesis.json too, and updated CMakeLists.txt -- is there anything else I need to update when moving that file? I was able to build, sync, and pass tests.

**Comment by ryanRfox** [comment]
Respectfully offering @nathanhourt some guidance, thus assisting me (and Core Team) to manage our maturing development workflow. This is a good reminder to me to complete the [Contribution Guide](https://github.com/bitshares/bitshares-core/wiki/Contribution-Guide) Wiki I started. We intend for a PR to reference an Issue (or multiple). GitHub automation will notice when you include "fix for #<IssueNumber>" and close the Issue when the PR is merged. We now have Issue Templates to guide creating a User Story for bug fixes, feature requests or build errors. This is likely classified as code clean up, so perhaps feature request. Within the Description of the Issue Template is a Core team Task List. We also use Labels to organize Issues. We include the Issues and PRs on our Project Boards for tracking. I believe [Feature Release 201904](https://github.com/bitshares/bitshares-core/projects/16) is appropriate, right @pmconrad ? Thanks again for your contributions!

**Comment by nathanhourt** [comment]
Replaced by #1592

**Pull request closed without merging**
