### PR TITLE
No spam sub function2

### PR DESCRIPTION
**Pull request by oxarbitrage**
Last version for:

https://github.com/bitshares/bitshares-core/issues/231

and:

https://github.com/bitshares/bitshares-core/pull/234

A node was compiled and tested by @svk31 with the code of this branch for the last few issues @svk31 reported at #234:

From @svk31 in telegram in regards to the node with the last code:

"Just tested creating, updating and closing a collateral position and it worked fine"

thanks @elmato for the hard work.

### CODE REVIEW

**Comment by svk31** [comment]
This looks ok to me, and from what I can tell it works as expected, however I'm not qualified to comment on the actual coding implementation. Specifically I'm not sure about the additional CPU impact of these changes.

**Comment by xeroc** [comment]
The changes to ` libraries/chain/db_block.cpp ` look to me as if they were breaking some design pattern, namely that the file has previously been independent of the operations while it now no longer is. This would lead to the need to add code there if you want to add functionality to the blockchain protocol (e.g. a new operation)

**Comment by vikramrajkumar** [comment]
@xeroc brings up a reasonable point. Perhaps we should create a separate `notify.cpp` file containing `get_impacted_account_visitor`, `operation_get_impacted_accounts`, `transaction_get_impacted_accounts`, `get_relevant_accounts`, `database::notify_changed_objects` in order to keep `db_block.cpp` from getting much bigger?

**Comment by oxarbitrage** [comment]
i like the idea of @vikramrajkumar. working on a separated file containing those functions.

**Comment by vikramrajkumar** [comment]
Superseded by #249 for reference

**Pull request closed without merging**
