### PR TITLE
Editline fix

### LINKED ISSUE #1948: Editline not being built/linked
**Build Error Description**
The latest testnet branch does not build nor link the editline library. As a result, some cli_wallet functionality is missing, in particular the new secure password entry method.

**Build Environment**
Details about the build environment, including the relevant required libraries. Much of this information can be found in the `CMakeFiles/CMakeOutput.log`. 
 - Host OS:             Linux
 - Source Branch/Tag:   latest testnet
 - Boost Version:       1.66.0
 - C++ Compiler:        gcc-7.4.1
 - CMake: 3.10.2

## CORE TEAM TASK LIST
- [ ] Evaluate `Build Error`
- [ ] Provide build guidance
- [ ] <OR> Create `Bug Report`

### LINKED ISSUE #1952: build error "could not bind to an lvalue of type 'const char [41]'"
**Instructions**
Please include a detailed Title above. Next, please complete the following sections below:
* Build Error
  ` Reference to type 'const std::string' (aka 'const basic_string<char, char_traits<char>, allocator<char> >') could not bind to an lvalue of type 'const char [41]'`
* Build Environment
    Xcode Version 10.1 (10B61)/ clang version 4.0.1 (tags/RELEASE_401/final)

* Console Logs (optional)
```
bitshares-core/libraries/fc/include/fc/variant.hpp:571:10: error: reference to type 'const std::string' (aka 'const basic_string<char, char_traits<char>,
      allocator<char> >') could not bind to an lvalue of type 'const char [41]'
         _FC_ASSERT( max_depth > 0, "Recursion depth exceeded!" );
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
**Build Environment**
Details about the build environment, including the relevant required libraries. Much of this information can be found in the `CMakeFiles/CMakeOutput.log`. 
 - Host OS:             macOS Mojave
 - Host Physical RAM    32GB
 - Source Branch/Tag:   master 
 - OpenSSL Version:     1.1.0g
 - Boost Version:       1.59
 - C++ Compiler:       clang version 4.0.1 (tags/RELEASE_401/final)

### PR DESCRIPTION
**Pull request by pmconrad**
Fix #1948 in release and fix #1952 by bumping fc.
Note the bump is not to fc/master but only includes the fix.

### CODE REVIEW

**Comment by abitmore** [comment]
Created branch [`for-core-3-3`](https://github.com/bitshares/bitshares-fc/tree/for-core-3-3) in FC to hold commits for 3.3 release. In case when there are new changes for 3.3, please create PRs against this branch.

**Comment by abitmore** [comment]
I'm confused. In https://github.com/bitshares/bitshares-fc/pull/125 editline for MinGW got removed. In https://github.com/bitshares/bitshares-fc/pull/121 editline for MinGW is re-added with no comment, is it correct? @crypto-ape please check.

**Comment by ryanRfox** [comment]
Also desire for @cwyyprog to review/comment on this issue related to Editline now available in MinGW. It seems you are familiar with building with MinGW. Are you able to build successfully and include Editline?

**Comment by ryanRfox** [comment]
@crypto-ape can you reach me on TG or WC? I use the same username as GH on those as well. Thanks.

**Comment by pmconrad** [comment]
> In bitshares/bitshares-fc#121 editline for MinGW is re-added with no comment,

Not really. Editline is in/excluded [here](https://github.com/bitshares/bitshares-fc/blob/master/CMakeLists.txt#L250-L255) depending on the `WIN32` flag which is true also for mingw builds. It is not possible to build editline with mingw.

Note: please keep this PR open for now, we may need to bump fc again for #1952

**Comment by crypto-ape** [comment]
Thanks @pmconrad, that is exactly it.

Before, there was a mismatch between the use of `MSVC` and `WIN32` cases.

As @pmconrad commented, `MINGW` implies `WIN32` so the https://github.com/bitshares/bitshares-fc/pull/121 should be ok.

IIRC I have compiled it successfully with MinGW on both Linux and Windows.

**Comment by abitmore** [comment]
Thanks for the clarification.

**Comment by ryanRfox** [comment]
Do we consider this one "done" @abitmore @pmconrad ? We have #1947 pending this one. Thanks

**Comment by abitmore** [comment]
@ryanRfox no, we wanted to (ab)use this PR to bump FC for #1952, so will add more commit(s) to this PR.

**Pull request merged**
