### PR TITLE
merge impacted into db_notify

### PR DESCRIPTION
**Pull request by xiangxn**
merge impacted into db_notify, see #845

### CODE REVIEW

**Comment by oxarbitrage** [comment]
need to send pull request to `develop` branch of bitshares.

**Comment by ryanRfox** [comment]
@xiangxn this PR needs to be rebased to develop, then you can change the destination to master.

**Comment by ryanRfox** [comment]
Moving this to `Done` temporarily. Once @xiangxn creates the new PR, we will add the reference here and remove it from the project board.

**Comment by ryanRfox** [comment]
See PR #1073

**Pull request closed without merging**
