### PR TITLE
Requires api_helper_indexes plugin to start node

### PR DESCRIPTION
**Pull request by abitmore**
#1836 introduced a `wlog` in constructor of `database_api_impl`, this PR changes it to `dlog` because `wlog` will cause disk space issue on API nodes (see https://github.com/bitshares/bitshares-core/pull/1799 and https://github.com/bitshares/bitshares-core/issues/1798).

### CODE REVIEW

**Comment by pmconrad** [comment]
This is a warning on purpose. API nodes *should* enable the plugin because otherwise clients will receive incomplete information. Changing the log level to debug means the node owner won't notice his configuration problem.

**Comment by abitmore** [comment]
Perhaps we add an option so the admins who really want to disable the plugin can disable the logging?

**Comment by pmconrad** [comment]
Hm, it feels wrong to add an option for a single log message.
IMO node owners who want to run API nodes without that plugin can post-process the logfiles to remove the message if it annoys them.
I can't really imagine a use-case where that makes much sense though. An API node is either public and *should* enable the plugin, or it's private and sees little API traffic and therefore only few of these messages. (Or maybe it's a private power user with a lot of API traffic - but I'd expect a power user to be able to tweak logging the way he wants it.)

**Comment by abitmore** [comment]
I think it's better to crash the node on start if we want to force the user to enable that plugin, than crash the node due to disk space issue after it's running for a few days. Better bother the admins once than twice.

Then, it would be a good idea to add an option to avoid the crash.

**Comment by abitmore** [comment]
Force pushed. @pmconrad please review.

**Comment by pmconrad** [comment]
IMO this option is annoying for non-API node admins. Please move the check into `application::reset_websocket...` so the option is only required for nodes that actually provide API endpoints.

**Comment by abitmore** [comment]
`application::reset_websocket()` is buried too deep in the call flow, so I added the checking in `main()`, the outcome should be the same.

**Pull request merged**
