### PR TITLE
Change operation_history to generic_index, #403

### PR DESCRIPTION
**Pull request by abitmore**
For #403

### CODE REVIEW

**Comment by oxarbitrage** [comment]
getting error when starting node with changes:

```
...
2404818ms th_a       undo_database.hpp:68          ~session             ] 10 assert_exception: Assert Exception
maybe_found != nullptr: Unable to find Object
    {"id":"0.0.0"}
    th_a  index.hpp:111 get

    {}
    th_a  undo_database.cpp:123 undo
terminate called after throwing an instance of 'fc::assert_exception'
Aborted
root@NC-PH-1346-07:~/bitshares/pull464/bitshares-core# 
```

**Comment by abitmore** [comment]
Sorry for that. New commit pushed.

**Comment by abitmore** [comment]
Note: perhaps should bump db_version when releasing.

**Comment by abitmore** [comment]
Some data from live test: this change saves around 500M of RAM with current chain (`head_block ~= 21614538`) and default config(`max-ops-per-account = 1000` and `partial-operations = true`).

**Comment by pmconrad** [comment]
Wow, I didn't expect that much!

**Pull request merged**
