### PR TITLE
libraries/wallet/CMakeLists.txt: add PWD to PERLLIB before running ge…

### LINKED ISSUE #409: build error Can't locate doxygen/perlmod/DoxyDocs
[ 80%] Generating api_documentation.cpp
Can't locate doxygen/perlmod/DoxyDocs.pm in @INC

### PR DESCRIPTION
**Pull request by piem**
…nerate_api_documentation.pl (closes #409)

### CODE REVIEW

**Comment by abitmore** [comment]
Can you elaborate why need this?

**Comment by piem** [comment]
@abitmore this fixes the documentation build failure described in #409 on current debian stable.

doxygen creates the files in `libraries/wallet/doxygen/`. when using doxygen 1.8.13-4+b1 and perl 5.24.1-3+deb9u2 (debian stable), these files are not found when running `perl`:

```
$ cd libraries/wallet
$ perl generate_api_documentation.pl /dev/stdout
Can't locate doxygen/perlmod/DoxyDocs.pm in @INC (you may need to install the doxygen::perlmod::DoxyDocs module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at generate_api_documentation.pl line 6.
```

One option is to add the current path to `PERLLIB` (note the proposed changes overwrite this variable if it was set before; `PERL5LIB` can still be used):
```
$ PERLLIB=$PWD perl generate_api_documentation.pl /dev/stdout | head
#include <set>
#include <graphene/wallet/api_documentation.hpp>
#include <graphene/wallet/wallet.hpp>

namespace graphene { namespace wallet {
   namespace detail 
   {
      struct api_method_name_collector_visitor
      {
         std::set<std::string> method_names;
```

Another option is to specify a relative include in `generate_api_documentation.pl`, but this requires adding a `chdir libraries/wallet`:

```diff
diff --git a/libraries/wallet/generate_api_documentation.pl b/libraries/wallet/generate_api_documentation.pl
index a3f333db..cf51804e 100755
--- a/libraries/wallet/generate_api_documentation.pl
+++ b/libraries/wallet/generate_api_documentation.pl
@@ -3,7 +3,7 @@
 use Text::Wrap;
 use IO::File;
 
-require 'doxygen/perlmod/DoxyDocs.pm';
+require './doxygen/perlmod/DoxyDocs.pm';
 
 my($outputFileName) = @ARGV;
 die "usage: $0 output_file_name" unless $outputFileName;
```

**Comment by oxarbitrage** [comment]
thank you very much for submitting this @piem . i don't have the last debian version to test but i can confirm older versions compile fine with the mod of this pull. if you can confirm it is working with last debian version we will be merging it asap. however we need pull requests to be sent to the `develop` branch instead of `master`. let me know if you can do this or if you want me to make it. 
thank you very much again and please don't hesitate to send other contributions to bitshares.

**Comment by piem** [comment]
hi @oxarbitrage! I confirm I can build the docs on debian stable (stretch) with this change. I will rebase and create a new PR against `develop`.

**Comment by piem** [comment]
moved to #479, closing

**Pull request closed without merging**
