### PR TITLE
[Docker] Build also cli_wallet.

### PR DESCRIPTION
**Pull request by Zapata**
Proposed implementation for: #837

Impact on image size is minimal, on my machine:
  zapata/bitshares-core        testnet             c0116c379fc2          37 hours ago         1.25GB
  zapata/bitshares-core        latest                40e7c3cd117e        39 hours ago        1.4GB
  bitshares/bitshares-core    testnet             f4d9edd8646d        12 days ago         1.27GB

Note that the sized showed on Docker hub is 3x off the reality (see docker/hub-feedback#331)

### CODE REVIEW

**Comment by Serpac** [comment]
REMOVE ME FORM ALL YOUR LIST YOU IDEIOTSSENT ME OVER 1000 EMAILS

**Comment by abitmore** [comment]
Off topic: I deleted a comment which was asking for not sending more notification email to him. Actually he can click the "unwatch" button on the top of the page.

**Comment by Zapata** [comment]
[As said](https://github.com/bitshares/bitshares-core/issues/837#issuecomment-383419375), we can remove `delayed_node` from the Docker image. I wait your feedback to confirm and amend the PR.

**Comment by abitmore** [comment]
@Zapata yes, please remove it. Thanks.

**Pull request merged**
