### PR TITLE
Change replay percentage to total block size processed #1289

### PR DESCRIPTION
**Pull request by cogutvalera**
PR for **"Change replay percentage to total block size processed #1289"**

### CODE REVIEW

**Comment by cogutvalera** [comment]
Thanks @pmconrad soon will push changes required.

**Comment by cogutvalera** [comment]
Pushed commit with required changes (just for the info)

**Comment by cogutvalera** [comment]
pushed new commit **"added percents by num and fixed possible overflow"**

**Comment by cogutvalera** [comment]
pushed new commit **"added replay percents to the log"** (see comment https://github.com/bitshares/bitshares-core/issues/985#issuecomment-423516682)

**Comment by pmconrad** [comment]
I'd suggest to wait for https://github.com/bitshares/bitshares-fc/pull/76, then bump fc before merging this one.

**Comment by cogutvalera** [comment]
@pmconrad Thanks !

**Comment by cogutvalera** [comment]
Can we merge this PR ?

**Comment by cogutvalera** [comment]
@pmconrad `fc` bumped in #985 (https://github.com/bitshares/bitshares-fc/pull/76)

**Comment by cogutvalera** [comment]
@pmconrad can we merge it too ?

Thanks !

**Pull request merged**
