### PR TITLE
Add get_block_operation_history API

### PR DESCRIPTION
**Pull request by abitmore**
PR for #243.

The API will return all operations inside a block or a transaction, including virtual operations.
```
/**
* @brief Get all operations inside a block or a transaction, including virtual operations
* @param block_num the number (height) of the block to fetch
* @param trx_in_block the sequence of a transaction in the block, starts from @a 0, optional.
*                     If specified, will return only operations of that transaction.
*                     If omitted, will return all operations in the specified block.
* @return a list of @a operation_history objects ordered by ID
*
* @note the data is fetched from @a account_history plugin, thus the result is possible to
*       be incomplete due to the @a partial-operations option configured in the API node.
*       For complete data, it is recommended to query from ElasticSearch where data is
*       maintained by @a elastic_search plugin.
*/
vector<operation_history_object> get_block_operation_history(
               uint32_t block_num,
               optional<uint16_t> trx_in_block = {} ) const;
```

### CODE REVIEW

**Comment by pmconrad** [comment]
IMO adding this call doesn't make much sense at this time, because it relies on data that is known to be incomplete for (almost) all nodes. I think we should discourage using node API for history data and not add this call.

**Comment by jmjatlanta** [comment]
Code looks good. If we can come up with a solid use case perhaps that will ease the concerns of @pmconrad . Since @xeroc made the original ticket, perhaps he can chime in.

**Comment by xeroc** [comment]
I agree with Peter, if the data cannot be obtained reliably, why have an API to obtain it.

**Comment by abitmore** [comment]
Closing. Let ES do the job.

**Pull request merged**
