### PR TITLE
Add logging.ini to docker config

### LINKED ISSUE #1723: logging.ini does not symlinked inside docker CT
Docker entrypoint bitsharesentry.sh creates symlink for config.ini, but not for logging.ini. Because of this, logging may appear as non-working.

### PR DESCRIPTION
**Pull request by pmconrad**
Resolves #1723

Note: IMO the docker build requires an overhaul. Will create a separate ticket for that.

### CODE REVIEW

**Comment by pmconrad** [comment]
`bitsharesentry.sh` creates symlinks in `/var/lib/bitshares/` that point to the config files in `/etc/bitshares/`.
I did it like that with `logging.ini` because that's the previous behaviour with `config.ini`. I don't like it either, which is why I created #2011. This PR only resolves the specific issue in #1723.

**Comment by oxarbitrage** [comment]
I still think you need to add the logging.ini into DockerFile. 

how do you see the logs this pull request is creating ?

**Comment by pmconrad** [comment]
I run a testnet container with bind-mounting a local directory for `/var/lib/bitshares` like this:
```
docker run --name bts-test -d -p 8091:8090 -p 1777:1776  -u bitshares --mount type=bind,src=/bigtmp/blockchains/BTS-Testnet,target=/var/lib/bitshares --restart always --init bitshares/bitshares-core:test-3.3.4
```
The logs should end up in the same directory, as usual under `logs/p2p`, `logs/default` and `logs/rpc`.
(`test-3.3.4` doesn't have these changes yet so it's probably a bad example. But it illustrates the idea.)

**Comment by pmconrad** [comment]
You're right. Fixed.

**Pull request merged**
