### PR TITLE
Add compile-time option TRACK_STANDBY_VOTES #987

### PR DESCRIPTION
**Pull request by abitmore**
PR for #987.

### CODE REVIEW

**Comment by oxarbitrage** [comment]
@jmjatlanta we need to merge this one before this one: https://github.com/bitshares/bitshares-core/pull/1099
#1099  one haves a test case: https://github.com/bitshares/bitshares-core/pull/1169

we should do the same here. 
do you have time to make it ?

the flow to merge the last @abitmore pull requests can be:

- merge https://github.com/bitshares/bitshares-core/pull/1099
- merge https://github.com/bitshares/bitshares-core/pull/1140 
- merge https://github.com/bitshares/bitshares-core/pull/1169
- merge test cases for 1140 if we do them.
- merge https://github.com/bitshares/bitshares-core/pull/1119 -> need cmake outout msg that build will be made with profile.

**Comment by jmjatlanta** [comment]
The test case in #1169 is a great template for this one (and 1099 as well).

I will create the tests in different but similarly named files to avoid merge conflicts. We can merge them into 1 file later.

I will probably need help verifying that I'm creating the environment that tests the actual change.

**Comment by oxarbitrage** [comment]
as discussed in telegram; @jmjatlanta will review https://github.com/bitshares/bitshares-core/pull/1099 and https://github.com/bitshares/bitshares-core/pull/1169 and we can merge them those if they are ready.

@oxarbitrage will do the test case for https://github.com/bitshares/bitshares-core/pull/1140

**Comment by pmconrad** [comment]
> Tests would be nice, but testing compile switches is a pain and near impossible to do in an automated way.

Good point. How about making it a runtime config switch instead. We already have a configurable setting in database, namely the checkpoints list, so I suppose adding more options is not an architectural breach. Opinions?

**Comment by abitmore** [comment]
> Good point. How about making it a runtime config switch instead. We already have a configurable setting in database, namely the checkpoints list, so I suppose adding more options is not an architectural breach. Opinions?

Will do. Actually run-time option is required in the user story.

**Comment by abitmore** [comment]
Replaced by #1191

**Pull request closed without merging**
