### PR TITLE
Merge release to master for 3.1.0

### PR DESCRIPTION
**Pull request by jmjatlanta**
See #1745 for release notes.

This PR will merge changes made to the develop branch to prepare for the upcoming release of version 3.1.0.

Notes: `GRAPHENE_CURRENT_DB_VERSION` was bumped, replay is required and will be automatic. The `docs` submodule was not bumped, as no new commits have been added.

### CODE REVIEW

**Comment by abitmore** [comment]
No.. current `develop` branch is for `3.2.0`, `release` is for `3.1.0`.

**Comment by jmjatlanta** [comment]
> No.. current `develop` branch is for `3.2.0`, `release` is for `3.1.0`.

Wasn't sure how it was done. Should I delete the current 'release' branch and create a new one called 'release'? Or an intermediate branch and merge into the current 'release' branch?

While the way I did it I still believe to be correct, I believe it is misleading. The 'develop_release' branch is based on the same commit as was sent to the testnet branch.

**Comment by abitmore** [comment]
We should have followed git-flow. See https://github.com/bitshares/bitshares-core/pull/1759.

**Comment by abitmore** [comment]
OK, now release is at 9f025e8 (was 51bc677).

**Comment by jmjatlanta** [comment]
Closing in favor of using the "release" branch instead of my "develop_release" branch.

**Pull request closed without merging**
