### PR TITLE
Update seed-nodes.txt

### PR DESCRIPTION
**Pull request by hammadsherwani**
Placing node at 9th place, "seed.bitshares.rocks:1776",           // bitshares      (USA)

### CODE REVIEW

**Review by abitmore — DISMISSED** [review]
Thanks a lot.

**Review by abitmore — APPROVED** [review]

**Comment by hammadsherwani** [comment]
Thanks.
What to do next at my end?

**Comment by abitmore** [comment]
Thank you @hammadsherwani and Brian. You're done. Please keep the node running and updated.

**Comment by hammadsherwani** [comment]
Thanks. Abit, Just need some understanding. where we see that our node is
open for others and serving the community.

Regards,
Hammad.

**Comment by abitmore** [comment]
Your node is running so it is already serving the community. Adding it to the list just makes it easier to be found by other new nodes.

**Comment by hammadsherwani** [comment]
Thanks Abit.

**Review by abitmore — APPROVED** [review]

**Pull request merged**
