### PR TITLE
change Graphene Witness Node

### PR DESCRIPTION
**Pull request by oxarbitrage**
to Bitshares Witness Node.

```
$ ./programs/witness_node/witness_node --help
Bitshares Witness Node:
  -h [ --help ]                         Print this help message and exit.
  -d [ --data-dir ] arg (="witness_node_data_dir")
...

```

### CODE REVIEW

**Comment by pmconrad** [comment]
Please also
* tests/benchmarks/main.cpp
* tests/generate_empty_blocks/main.cpp
* libraries/wallet/doxygen/perlmod/DoxyDocs.pm
* libraries/wallet/Doxyfile.in
* libraries/wallet/include/graphene/wallet/wallet.hpp
* libraries/protocol/include/graphene/protocol/asset.hpp
* libraries/protocol/include/graphene/protocol/proposal.hpp
* libraries/protocol/include/graphene/protocol/worker.hpp
* libraries/protocol/include/graphene/protocol/vote.hpp
* libraries/plugins/witness/witness.cpp
* programs/genesis_util/genesis_update.cpp

IMO we should use a different name in testnet, when creating the next release. Please open an issue for that.
Also it would be good to reduce the number of places where the literal name is used, to avoid future conflicts when merging to testnet. Didn't we have a macro for the name? Is it possible to expand macros within a doc comment?

**Comment by oxarbitrage** [comment]
I don't think we need the macro for the comments. A comment that says `@brief The price struct stores asset prices in the Bitshares system.` is valid in all the branches.

**Comment by abitmore** [comment]
I think the correct word is `BitShares` but not `Bitshares`.

**Comment by oxarbitrage** [comment]
Agree on the name @abitmore and changed.

**Pull request merged**
