### PR TITLE
Hello plugin

### PR DESCRIPTION
**Pull request by xeroc**
My first baby steps on graphene.
I got it compiled even though it technically doesn't "do" anything and I am even unsure as to how to enable the plugin at run time.

This PR serves as a place to discuss how to do a demo plugin for others to look into ..

### CODE REVIEW

**Comment by pmconrad** [comment]
Nice! ... for a start, I think this should be extended a little, maybe register db api listeners or something. And hello should do something, like write "hello" to the log, return head block number or whatever. 

Plugins cannot be added at runtime, they have to be compiled in. But with #288 it will be possible to en-/disable them at runtime.

**Comment by xeroc** [comment]
I have made some more changes to the hello_plugin (https://github.com/bitshares/bitshares-core/compare/develop...bitshares:hello_plugin?expand=1) .. and I can now see it (the plugin) loading (`startup()`) when running the witness_node ... however, the API is still not available .. any input is highly appreciated .. i don't know where to begin in solving this ..

**Comment by xeroc** [comment]
Ha .. turns out I did everything right and i just messed up during compilation :)

@pmconrad, the hello() api call no returns the head block number from the database.

I'll see if i can write a 'tutorial' on what needs to be done to get a custom plugin integrated .. expect noobish C++ experience ;)

**Comment by oxarbitrage** [comment]
@xeroc do you think you can resolve the conflicts ? if you don't have time or whatever let me know, i can give it a try.

**Comment by xeroc** [comment]
@oxarbitrage Fixed the merge .. conflicts happend because we no have the delayed node as plugin too

**Comment by oxarbitrage** [comment]
closing pull as we are not going to merge it but have it in `bitshares-core/hello-plugin` branch and point documentation there.

**Comment by oxarbitrage** [comment]
https://github.com/bitshares/bitshares-core/tree/hello_plugin

**Comment by oxarbitrage** [comment]
the specific commits needed to add a new plugin(hello_plugin demo in this case) are at: https://github.com/bitshares/bitshares-core/commit/eb0ab2174c37b7be5c8fc8be63845bd2afcfacbd

**Pull request closed without merging**
