### PR TITLE
cli_wallet doesn't exit on quit nor EOR #1216

### PR DESCRIPTION
**Pull request by cogutvalera**
PR for #1216

### CODE REVIEW

**Comment by cogutvalera** [comment]
to not raise a signal in quit() just avoid early termination in cli_test, but if we capture signal in cli_test then we can raise signal in quit() command in cli_wallet, why not ? the main reason was not to raise signal in quit() command in cli_wallet as mentioned @abitmore earlier not to early terminate cli_test and that's all, but we can handle early termination in cli_test and though we won't have any problems in cli_test, is not true ?

**Comment by cogutvalera** [comment]
look please my last comment here https://github.com/bitshares/bitshares-core/issues/1216#issuecomment-409713634

**Comment by pmconrad** [comment]
A library shouldn't raise arbitrary signals, just like it shouldn't exit(). It should communicate its results properly to the caller, and leave them to handle the situation as they see fit.

**Comment by cogutvalera** [comment]
yes sure ! you're absolutely right ! will make changes now to raise signal in cli caller and not inside wallet lib

**Pull request closed without merging**
