### PR TITLE
Integrating cURL into cmake

### PR DESCRIPTION
**Pull request by abitmore**
The original PR is #1329, will continue the work in this PR.

Todo:
- [ ] update wiki according to https://github.com/cwyyprog/bitshares-core/wiki/WinDevEnv
- [ ] test in Windows

### CODE REVIEW

**Comment by ryanRfox** [comment]
@jmjatlanta Do you have time and an environment to test this?

**Comment by jmjatlanta** [comment]
I have a macOS and Ubuntu 18.04 environment. I need to take a longer look at my Windows VM and figure out why I can't build there. It has never worked (seems to be something fishy with cmake's findBoost.cmake). I will attack mac and linux first, and then see what I can do for Windows.

**Comment by oxarbitrage** [comment]
added https://github.com/bitshares/bitshares-core/wiki/WinDevEnv

**Comment by oxarbitrage** [comment]
added WinDevEnv to wiki index https://github.com/bitshares/bitshares-core/wiki#building

**Pull request merged**
