### PR TITLE
Support compiling with C++17/C++2a

### PR DESCRIPTION
**Pull request by emfrias**
Bitshares used 'using namespace std' in several places, and this
caused conflicts between fc::variant and the new std::variant.
Fixed by just importing the specific identifiers we use from
namespace std.

### CODE REVIEW

**Comment by abitmore** [comment]
@emfrias please send pull request to `develop` branch.

**Comment by abitmore** [comment]
Please undo the change on FC submodule.

**Comment by pmconrad** [comment]
Looks good, except for the fc downgrade.

**Comment by jmjatlanta** [comment]
> @jmjatlanta can you test this on windows?

Tested on Windows 10 / Boost 1.69 / Visual Studio 2017 with no problems.

Note unrelated to this ticket: With the current status of fc and bitshares-core, to compile with Visual Studio 2017 you must
```
cd libraries/fc
git checkout master
cd ../../
```
And then edit the file `libraries/chain/include/graphene/chain/protocol/types.hpp` and remove the section between the //TODO comments near the top. Then compile as normal. For me that is:
```
cmake -G %VS_VERSION% -A x64 -DBOOST_ROOT=%BOOST_DIR% -DCURL_STATICLIB=ON -DCURL_LIBRARY=%CURL_DIR%\lib\libcurl_imp.lib -DCURL_INCLUDE_DIR=%CURL_DIR%\include -DOPENSSL_CONF_SOURCE="C:\Program Files\Common Files\SSL\openssl.cnf"
cmake --build . --target install --config Release
```
(replace the variables with values specific to your environment)

**Pull request merged**
