### PR TITLE
Unit test + log message related to issue #338

### PR DESCRIPTION
**Pull request by pmconrad**

### CODE REVIEW

**Comment by pmconrad** [comment]
I'm seeing about 200 of these log messages during replay.

**Comment by pmconrad** [comment]
Sorry about that. I must have messed up when switching branches between tests or something.

**Comment by oxarbitrage** [comment]
compiles now, thanks for the changes. as @xeroc stated there are 200+ cases in the bitshares chain:

```
root@NC-PH-1346-07:~/bitshares/pull341/bitshares-core# cat out.txt | grep -c Multiple
222
root@NC-PH-1346-07:~/bitshares/pull341/bitshares-core#
```

in the market_tests there are 16 failures:

```
*** 16 failures detected in test suite "Master Test Suite"
root@NC-PH-1346-07:~/bitshares/pull341/bitshares-core/tests# ./chain_test -t market_tests  -l error
```

please confirm if the number of failures is the expected so we can merge it.

**Comment by oxarbitrage** [comment]
@alexpmorris can you check with us if the 16 failing cases in the tests are the expected results. I can paste full log of the run.

**Comment by alexpmorris** [comment]
There are some failed test cases I saw (about 8 or so) that seem unrelated to my code, such as this:

`/home/vm/bitshares-core/tests/tests/basic_tests.cpp(54): error: in "basic_tests/valid_name_test": check !is_valid_name( "a" ) has failed`

Also, my code shouldn't even be active for the older tests, as the new code must be activated by setting the extension: `{"isCoreBuySell"=true/false}`.  Otherwise, it reverts to the original behavior, which would apply to margin-call (and other) activity.

I did make a bunch of changes since what I'm seeing above though, for example `create_sell_order_with_flag()` has been replaced with `create_sell_order_with_ext`.  However, I forget to move it from optest.cpp into database_fixture.cpp (it was faster for me to test/recompile from there).  

I moved it to database_fixture.cpp/hpp, and made the necessary parameter adjustments in the optest.cpp tests.  All the latest changes can be found below:

https://github.com/alexpmorris/bitshares-core/commits/order-rounding-fix

**Comment by abitmore** [comment]
Since we've split #338 to multiple issues, we'd better split this PR to multiple PR's.

**Comment by pmconrad** [comment]
Moved the original commits into separate PRs. Unsure about Alex's test cases.

**Comment by alexpmorris** [comment]
My test cases were meant to confirm functionality of the code to help deal with the rounding issues on the DEX, So they wouldn't necessarily apply or be useful until those changes *(or some variation thereof)* were implemented at some point.

**Comment by abitmore** [comment]
Closing this PR so far. Will check Alex's commits later, but not here.

**Pull request closed without merging**
