### PR TITLE
fixed #809 issue, open log file in append mode

### LINKED ISSUE #809: Log file of current hour gets overwritten by default
Steps to reproduce:
* change `config.ini` so default log will be written to file
```
# declare an appender named "default" that writes messages to default.log
[log.file_appender.default]
filename=logs/default/default.log
# filename can be absolute or relative to this config file

# route any messages logged to the default logger to the "stderr" logger and "default" logger we
# declared above, if they are info level are higher
[logger.default]
level=info
appenders=stderr,default
```
* start `witness_node`
* stop `witness_node`
* check log file (witness_node_data_dir/logs/default/default.log)
* start `witness_node` again
* check log file (witness_node_data_dir/logs/default/default.log)

The log file will be overwritten on restart.

IMHO the default behavior should be appending but not overwriting.

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [x] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
  - [x] Issue estimation: 2 hours
  - [x] Issue assigned to @nanomobile 
- [ ] Perform QA/Testing
- [ ] Update Documentation

### PR DESCRIPTION
**Pull request by nanomobile**
https://github.com/bitshares/bitshares-core/issues/809

- [ ] rebase this PR after merged https://github.com/bitshares/bitshares-fc/pull/56

### CODE REVIEW

**Comment by ryanRfox** [comment]
@pmconrad May I request you to review the docker failure? I don't understand why the PRs from different users are running tests from different repos (if I understand the logs correctly). Here is what I find: 
image

**Comment by ryanRfox** [comment]
Perhaps it is related to this open PR within FC. https://github.com/bitshares/bitshares-fc/pull/56

**Comment by abitmore** [comment]
Need to create a new PR or rebase this one after merged https://github.com/bitshares/bitshares-fc/pull/56.

**Comment by nanomobile** [comment]
is ready

**Comment by nanomobile** [comment]
I think we don't need pull request for this issue in bitshares-core repo because we have pull request in bitshares-fc repo, am I right ? can I close this pull request ?

**Comment by abitmore** [comment]
@nanomobile as I wrote above:
> Need to create a new PR or rebase this one **after** merged bitshares/bitshares-fc#56.

Nothing to do right now.

**Comment by cogutvalera** [comment]
ok sure ! Thanks !

**Comment by abitmore** [comment]
Only need to bump FC once, which will be done in #1104. Closing this one.

**Pull request closed without merging**
