### PR TITLE
bump the docs

### PR DESCRIPTION
**Pull request by oxarbitrage**

### CODE REVIEW

**Comment by abitmore** [comment]
Git-Flow says we should only update wiki when merging to master. However, we've already updated wiki when developing (even before merging to develop), which may lead to confusion, E.G. if we updated develop branch to be compatible to boost 1.70 but haven't update master yet (so master is not compatible), we should not mention in wiki that current code is compatible to boost 1.70. According to this logic, we can only bump docs submodule (to release branch) in the last minute before merging to master.

**Comment by oxarbitrage** [comment]
should we change the base of this pull to `develop` so we will have the updated wiki in the `testnet` release ?

**Comment by jmjatlanta** [comment]
How these Github wikis work confuses me. Can we not make branches of it and tie a bump to a specific commit? Does that solve the issue @abitmore has brought up?

I do not see where our git-flow document says we should only bump when merging to master. I may just not see it. But regardless, I think we need to work it out and clarify the "bump the docs" procedure in the git-flow document to make next time easier.

Let me know how I can help.

**Comment by abitmore** [comment]
The Wiki itself is open to public with URL https://github.com/bitshares/bitshares-core/wiki, it has only one branch, we don't mention `develop` branch in Wiki, so its latest content should be bound to the default `master` branch. That said, if `master` branch don't support A, we should not say we support A in Wiki. That's why we should only update Wiki when merging to master.

On the other hand, Wiki is a submodule of bitshares-core repository (the `docs` directory), which has a revision, it's desired that `git checkout master; git submodule update` command will get corresponding doc, so we need to bump revision of docs when merging to master.

A side effect of this approach is that docs of develop branch will be stale at most of the time.

**Comment by abitmore** [comment]
I don't know if Wiki can have branches.

**Comment by abitmore** [comment]
Please check if this PR is bumping to the latest revision.
Please check if we still need to update some docs.

**Pull request merged**
