### PR TITLE
Testnet consensus release

### PR DESCRIPTION
**Pull request by oxarbitrage**
Merges the `testnet_release` into `testnet` with hardfork activation dates  **Thursday, February 28, 2019 2:02:00 PM**

All testnet block producers must upgrade, API nodes are recommended to upgrade too.

### CODE REVIEW

**Comment by pmconrad** [comment]
Can we include a snapshot comparison into our standard release procedure?
We didn't do it for the last one, but I think it would generally be a good idea.

**Comment by oxarbitrage** [comment]
I created the snapshots between `testnet` and `testnet_release`.

When comparing i found 3 objects types that changed their structure by the code we are about to merge, i think they are all ok and explainable by our pull request :

1) `1.3.X` objects changed `extensions` field format from `[]` to `{}`. #1268 
2) `1.13.0` objects added `balance_type` field. #1268
3) `2.4.0` objects added `maintenance_collateralization` field. #1270 

Also updated this document: https://github.com/oxarbitrage/documentation/blob/master/snapshot.md 

Plan to link it in the release steps of the git flow(https://github.com/bitshares/bitshares-core/wiki/Git-Flow)

**Comment by abitmore** [comment]
We should bump DB_VERSION.

**Comment by oxarbitrage** [comment]
pls check https://github.com/bitshares/bitshares-core/pull/1615

**Comment by oxarbitrage** [comment]
changed bump db to hardfork branch here https://github.com/bitshares/bitshares-core/pull/1616

**Comment by oxarbitrage** [comment]
bringing bump db from hardfork at https://github.com/bitshares/bitshares-core/pull/1617

**Pull request merged**
