### PR TITLE
 Market his: make _meta local, fix fee_refund test

### PR DESCRIPTION
**Pull request by abitmore**
PR for #615

### CODE REVIEW

**Comment by abitmore** [comment]
Best make a replay test to see whether it will cause wrong data on `get_ticker` API and etc.

**Comment by oxarbitrage** [comment]
> Best make a replay test to see whether it will cause wrong data on get_ticker API and etc.

i did already, not fully replied but calls continue working ok.

**Comment by abitmore** [comment]
> i did already, not fully replied but calls continue working ok.

Need to make sure the data returned by old and new API matches. Thanks.

**Comment by abitmore** [comment]
Should be OK. Merging.

**Pull request merged**
