### PR TITLE
Store price in fill_order_operation, for #449

### LINKED ISSUE #449: Market history dust orders mess up charts
I'm sure you've all seen charts that look like this in the GUI:
image

The main reason for this is partial fills leaving behind dust orders with only 1 satoshi remaining on the sell or buy side, which can only execute at one specific price due to the price being defined as the ratio of buy/sell quantities. This price can be quite different from the originally defined price of the order, causing these jumps in the price seen in the chart.

One way of improving on this is to filter out these dust orders when constructing the buckets, which I've implemented in this commit: https://github.com/bitshares/bitshares-core/commit/aaa82a871a79c08fc4dc67fc7e9ae82ada75f6b9

Now I'm no C programmer so that code is probably terrible so if someone can clean it up that's great, but it works and proves that filtering can improve the display of the market history. Compare the first screenshot to this second one of the same market and period with my local node running my fix:

image

There are still some weird spikes, but it's much improved.

### PR DESCRIPTION
**Pull request by abitmore**
Trying to fix #449. Needs testing.

### CODE REVIEW

**Comment by abitmore** [comment]
I'm going to refactor `get_ticker` in order to improve performance a bit. After it's done, will start a new discussion about further improvements.

**Comment by svk31** [comment]
Trying to test this today, but I recently upgraded Ubuntu to 17 and now I'm having a hard time compiling Bitshares again.

**Comment by abitmore** [comment]
@svk31: @oxarbitrage once said he has an API node for you to test this.

**Comment by abitmore** [comment]
Found a bug about swapping `base` and `quote`. Fixing.

**Comment by oxarbitrage** [comment]
sent node url with pull to sivek including last commit added today. he will be testing it tomorrow.

**Comment by svk31** [comment]
I've tested the GUI using oxarbitrage's node and it's certainly a big improvement. If the performance of your solution is acceptable then it would be great to include this in the next release.

Here's an example in the CNY:USD market, at 1m zoom and 1d candles

Before:
image

After:
image

**Comment by abitmore** [comment]
The peak price on the latter image is `7.57 CNY/USD` recorded at `2017-11-02 08:12:42 UTC`.

On [block #21437324](https://cryptofresh.com/b/21437324), `bts-forever` placed an order: `wants 5,098 USD for 38,592 CNY ` with price `7.57`, after most of it got filled as a taker, a dust of `0.0013 CNY` was left on the market, then the dust got filled on [block 21437325](https://cryptofresh.com/b/21437324) as a maker, so the price got recorded as intended.

Before the fix, price of that order will be shown as `0.0013 CNY / 0.0001 USD = 13 CNY/USD`.

Performance would be improved after #454 is done.

**Comment by abitmore** [comment]
> `get_ticker` now returning time(maybe add this also to `get_24_volume`?):

Good idea. Will do.

**Comment by abitmore** [comment]
Apparently the `amount` and `value` data returned by `get_trade_history` and `get_trade_history_by_sequence` are usually inaccurate due to #144, also `price` is not graceful. Will fix them in another PR.

**Comment by abitmore** [comment]
Merged so far. If there is anything please submit a new issue.

**Comment by landry314** [comment]
The new update in the GUI has a much WORSE dust-trade-wick issue than the last release. Is there any progress? This is a huge downfall in the BitShares GUI.

**Comment by oxarbitrage** [comment]
please check https://github.com/bitshares/bitshares-core/issues/563

**Comment by svk31** [comment]
Nothing has changed in the GUI that would affect this. Most likely you've connected to an API node that does not contain the recent fixes. The Bitshares Infrastructure nodes use the recent witness_node versions and have much better data for the charts.

**Pull request merged**
