### PR TITLE
Testnet release to add HTLC Blacklist functionality

### PR DESCRIPTION
**Pull request by jmjatlanta**
This PR will release the blacklist functionality to HTLCs in TESTNET. At contract create time, white/blacklists will be checked.

### CODE REVIEW

**Comment by abitmore** [comment]
Do we need another hardfork? Has anyone broke the unsaid rule in testnet?

**Comment by jmjatlanta** [comment]
No one has done it to my knowledge.

**Comment by pmconrad** [comment]
Wait with merge until #1656 is in?

**Comment by jmjatlanta** [comment]
> Wait with merge until #1656 is in?

If we can get 1656 in, that would be great. But I feel we want this boat to sail and we're being held up by a knot in a line.

**Comment by abitmore** [comment]
I prefer containing #1656 in next release. Otherwise there would be an API change after the release which would bring more confusion.

**Comment by jmjatlanta** [comment]
At first glance, it looks like the new transaction size code is preventing a STEALTH test in cli_test. I would guess it is a problem already in the TESTNET branch, but I am investigating.

**Comment by jmjatlanta** [comment]
Earlier test failure was unrelated to this PR. New PR created #1665

**Pull request merged**
