### PR TITLE
update date of requirements table

### PR DESCRIPTION
**Pull request by oxarbitrage**
related to https://github.com/bitshares/bitshares-core/pull/1376

### CODE REVIEW

**Comment by abitmore** [comment]
We'd better get an accurate number. Who have a full node running?

**Comment by pmconrad** [comment]
If we can't get an up-to-date number we should not bump the date.

**Comment by oxarbitrage** [comment]
I was able to get some input from @dls-cipher in the bitshares nodes admin channel in telegram. 

134.1GB was June metrics, right now the estimate of real RAM is of 160G however a full node according to his experience will synchronize and run fine for a while with 128G RAM and 200G of SSD.

I suppose some of the SSD is used as RAM at some point and will be good enough for us by now.

**Comment by pmconrad** [comment]
SSD isn't used as RAM. Swapspace at most, but that's still orders of magnitude slower.
I think we should document 160G for the full node. It's not a recommended setup anyway.

I have also experienced that a long-running node uses much more RAM than right after restart, i. e. with the same database size. Either that's due to fragmentation, or we have leaks.

**Pull request merged**
