### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ashaman-**
Update RAM usage of full API node

### CODE REVIEW

**Comment by Ashaman-** [comment]
You're welcome!

**Comment by abitmore** [comment]
After merged #422, by default, new nodes aren't "full nodes" anymore, so don't need much RAM. This need to be documented.

By the way, I think it's OK to merge document changes to master branch before releases. Anyway, if done so, also need to cherry-pick or submit another PR to develop branch.

**Comment by oxarbitrage** [comment]
What if we add a link to the `develop` branch readme in the `master` o have an always up to date reference?

To do it we need to:
- send a pull request to the `readme `of the `develop `with text similar to "click link to see always up to date readme from develop branch".
- merge `develop` to `branch`(next release).

With this, on `develop` branch link will point to itself and in `master` to `develop` readme file.

Will need to wait until the next release to implement but will avoid merging to `master` directly, cherrypicking, etc.

**Comment by oxarbitrage** [comment]
please check https://github.com/bitshares/bitshares-core/pull/548/files now, i added some changes.

**Comment by pmconrad** [comment]
> What if we add a link to the develop branch readme in the master to have an always up to date reference?

The documentation in develop might be too up-to-date, i. e. document behaviour that is not yet in master.

**Comment by oxarbitrage** [comment]
> The documentation in develop might be too up-to-date, i. e. document behaviour that is not yet in master.

yea, i am not sure if it will be a good idea. what i don't like much is to update the README of the master directly. I guess we can support it if you guys think is the best, we need to include it to the protocol at https://github.com/bitshares/bitshares-core/wiki/Git-Flow if we do so.

**Comment by pmconrad** [comment]
Direct changes on master will sooner or later lead to merge conflicts and should therefore be avoided.
However, IMO the strict git flow *can* be relaxed a little for non-code files like documentation. Decide on a case-by-case basis, balancing urgency against possible additional work in the future when merge conflicts arise.

**Comment by oxarbitrage** [comment]
1 additional approve required to merge this changes to the develop README.

**Comment by abitmore** [comment]
The long change history looks not so good for me. Best rebase or cherry-pick before merging.

**Comment by oxarbitrage** [comment]
the best will be to discard this one and add a new one against the `develop` branch to avoid the long history. @Ashaman- do you want to do this or want me to do it ?

**Pull request closed without merging**
