### PR TITLE
Release Candidate

### PR DESCRIPTION
**Pull request by pmconrad**
This PR merges everything that went into the last testnet release plus the last-minute-changes into master in preparation for the release.
The hardfork date is set to 2017-11-27 14:40 UTC.
Tested locally with a full replay.

### CODE REVIEW

**Comment by abitmore** [comment]
Need to merge the new soft fork code?

**Comment by pmconrad** [comment]
Yes, and possibly your proposed fix as well.

**Comment by abitmore** [comment]
OK. For those who have interest in the proposed fix, a PR is created: https://github.com/bitshares/bitshares-core/pull/435

**Comment by pmconrad** [comment]
Please stand by - will merge #437 and then update this one.

**Comment by pmconrad** [comment]
Ok - merged the latest fixes + resolved a conflict with a recent merge into master.
I also reduced the logging for #353 because it has caused a lot of confusion among testnet witnesses.
Please make a final review and merge so we can tag a release at last.

**Comment by oxarbitrage** [comment]
i fully synchronized the release candidate, all good. i am about to merge. question: the tests cases for issue443 are still failing, is this expected ?

```
unknown location(0): fatal error in "issue_433_test": unknown type
/root/bitshares/bitshares-core/tests/common/database_fixture.cpp(216): last checkpoint

*** 1 failure detected in test suite "Master Test Suite"
root@NC-PH-1346-07:~/bitshares/bitshares-core# 
```

**Comment by oxarbitrage** [comment]
asked @pmconrad . the issue is the same as in the develop branch and test will succeed again after hardfork date passes. merging the full thing to master.

**Comment by julian1** [comment]
It's really great to see people working on this bitshares code again!

**Pull request merged**
